(defpackage #:clautolisp.autolisp-builtins-core
  (:use #:cl)
  (:import-from #:clautolisp.autolisp-runtime
                #:autolisp-catch-all-error
                #:autolisp-catch-all-error-message
                #:blackboard-ref
                #:blackboard-set
                #:current-document-namespace-ref
                #:current-document-namespace-set
                #:export-function-to-current-document
                #:import-functions-from-application
                #:import-function-from-current-document
                #:autolisp-file
                #:autolisp-termination
                #:autolisp-namespace-exit
                #:autolisp-runtime-error
                #:autolisp-runtime-error-errno
                #:autolisp-string
                #:autolisp-file-stream
                #:autolisp-function-list-definition
                #:autolisp-current-directory
                #:autolisp-load-file
                #:set-autolisp-errno
                #:autolisp-support-paths
                #:autolisp-trusted-paths
                #:call-with-autolisp-error-handler
                #:call-autolisp-function
                #:default-evaluation-context
                #:make-autolisp-string
                #:make-autolisp-catch-all-error
                #:make-autolisp-file
                #:make-autolisp-usubr
                #:resolve-autolisp-function-designator
                #:autolisp-string-value
                #:autolisp-symbol
                #:autolisp-symbol-name
                #:autolisp-symbol-value
                #:autolisp-symbol-value-bound-p
                #:autolisp-atom
                #:autolisp-eval
                #:autolisp-false-p
                #:autolisp-listp
                #:autolisp-not
                #:autolisp-null
                #:autolisp-read-from-string
                #:autolisp-subr
                #:autolisp-subr-name
                #:autolisp-true-p
                #:autolisp-type
                #:autolisp-vl-symbol-name
                #:autolisp-vl-symbolp
                #:autolisp-vl-symbol-value
                #:close-autolisp-file
                #:intern-autolisp-symbol
                #:make-autolisp-subr
                #:propagate-variable
                #:set-autolisp-function-list-definition
                #:set-autolisp-symbol-function)
  (:export
   #:*core-builtin-names*
   #:core-builtins
   #:find-core-builtin
   #:install-core-builtins
   #:autolisp-value->string))
