(defpackage #:clautolisp.autolisp-builtins-core
  (:use #:cl)
  (:import-from #:clautolisp.autolisp-runtime
                #:autolisp-catch-all-error
                #:autolisp-catch-all-error-message
                #:blackboard-ref
                #:blackboard-set
                #:current-document-namespace-ref
                #:current-document-namespace-set
                #:export-function-to-current-document
                #:import-functions-from-application
                #:import-function-from-current-document
                #:autolisp-file
                #:autolisp-termination
                #:autolisp-namespace-exit
                #:autolisp-runtime-error
                #:autolisp-runtime-error-code
                #:autolisp-runtime-error-errno
                #:autolisp-string
                #:autolisp-file-stream
                #:autolisp-function-list-definition
                #:autolisp-current-directory
                #:autolisp-load-file
                #:set-autolisp-errno
                #:autolisp-support-paths
                #:autolisp-trusted-paths
                #:call-with-autolisp-error-handler
                #:call-autolisp-function
                #:default-evaluation-context
                #:make-autolisp-string
                #:make-autolisp-catch-all-error
                #:make-autolisp-file
                #:make-autolisp-usubr
                #:resolve-autolisp-function-designator
                #:autolisp-string-value
                #:autolisp-symbol
                #:autolisp-symbol-name
                #:autolisp-symbol-value
                #:autolisp-symbol-value-bound-p
                #:autolisp-atom
                #:autolisp-eval
                #:autolisp-false-p
                #:autolisp-listp
                #:autolisp-not
                #:autolisp-null
                #:autolisp-read-from-string
                #:autolisp-subr
                #:autolisp-subr-name
                #:autolisp-usubr
                #:autolisp-usubr-name
                #:autolisp-true-p
                #:autolisp-type
                #:autolisp-vl-symbol-name
                #:autolisp-vl-symbolp
                #:autolisp-vl-symbol-value
                #:close-autolisp-file
                #:intern-autolisp-symbol
                #:make-autolisp-subr
                #:propagate-variable
                #:set-autolisp-function-list-definition
                #:set-autolisp-symbol-function
                #:current-evaluation-dialect
                #:current-evaluation-host
                #:autolisp-ename
                #:autolisp-ename-value
                #:make-autolisp-ename
                #:autolisp-pickset
                #:autolisp-pickset-value
                #:make-autolisp-pickset
                #:autolisp-vla-object
                #:autolisp-vla-object-value
                #:make-autolisp-vla-object
                ;; Phase 14a/b — host-object ontology + reactors
                #:reactor
                #:make-reactor
                #:reactor-id
                #:reactor-kind
                #:reactor-scope
                #:reactor-callbacks
                #:reactor-owners
                #:reactor-data
                #:reactor-active-p
                #:reactor-persistent-p
                #:reactor-notification
                #:reactor-document
                #:reactor-type-scope
                #:reactor-type-keywords
                #:add-reactor-to-document
                #:add-reactor-to-session
                #:remove-reactor-from-document
                #:remove-reactor-from-session
                #:all-document-reactors
                #:all-application-reactors
                #:all-session-reactors
                #:document-namespace-persistent-reactor-index)
  (:import-from #:clautolisp.autolisp-runtime
                #:autolisp-safearray
                #:autolisp-safearray-value
                #:make-autolisp-safearray
                #:autolisp-variant
                #:autolisp-variant-value
                #:make-autolisp-variant)
  (:import-from #:clautolisp.autolisp-dcl
                #:dcl-runtime-load-dialog
                #:dcl-runtime-unload-dialog
                #:dcl-runtime-new-dialog
                #:dcl-runtime-start-dialog
                #:dcl-runtime-done-dialog
                #:dcl-runtime-action-tile
                #:dcl-runtime-set-tile
                #:dcl-runtime-get-tile
                #:dcl-runtime-mode-tile
                #:dcl-runtime-client-data
                #:dcl-runtime-set-client-data
                #:install-default-renderer
                #:make-terminal-renderer)
  (:import-from #:clautolisp.autolisp-host
                #:host-entget
                #:host-entmod
                #:host-entmake
                #:host-entmakex
                #:host-entdel
                #:host-entupd
                #:host-entlast
                #:host-entnext
                #:host-handent
                #:host-ssget
                #:host-ssadd
                #:host-ssdel
                #:host-ssname
                #:host-sslength
                #:host-ssmemb
                #:host-ssgetfirst
                #:host-sssetfirst
                #:host-tblsearch
                #:host-tblnext
                #:host-tblobjname
                #:host-getvar
                #:host-setvar
                #:host-prompt
                #:host-initget
                #:host-getstring
                #:host-getint
                #:host-getreal
                #:host-getpoint
                #:host-getcorner
                #:host-getdist
                #:host-getangle
                #:host-getorient
                #:host-getkword
                #:host-vlax-create-object
                #:host-vlax-get-object
                #:host-vlax-release-object
                #:host-vlax-get-property
                #:host-vlax-put-property
                #:host-vlax-invoke-method
                #:host-vlax-property-available-p
                #:host-vlax-method-applicable-p)
  (:export
   #:*core-builtin-names*
   #:core-builtins
   #:find-core-builtin
   #:install-core-builtins
   #:autolisp-value->string))
