(defpackage #:clautolisp.autolisp-runtime.tests
  (:use #:cl)
  (:import-from #:fiveam
                #:def-suite
                #:in-suite
                #:is
                #:run
                #:explain!
                #:results-status
                #:test)
  (:import-from #:clautolisp.autolisp-runtime
                #:autolisp-runtime-error
                #:autolisp-runtime-error-code
                #:autolisp-runtime-error-details
                #:autolisp-string
                #:autolisp-string-value
                #:autolisp-symbol
                #:autolisp-symbol-function
                #:autolisp-symbol-function-bound-p
                #:autolisp-symbol-name
                #:autolisp-symbol-value
                #:autolisp-symbol-value-bound-p
                #:autolisp-type
                #:autolisp-vl-symbol-name
                #:autolisp-vl-symbolp
                #:autolisp-vl-symbol-value
                #:autolisp-listp
                #:autolisp-atom
                #:autolisp-eval
                #:autolisp-eval-progn
                #:autolisp-boundp
                #:autolisp-errno
                #:autolisp-function-list-definition
                #:autolisp-load-file-in-context
                #:autolisp-null
                #:autolisp-not
                #:autolisp-read-from-string
                #:bind-dynamic-variable
                #:blackboard-ref
                #:blackboard-set
                #:call-with-autolisp-error-handler
                #:current-evaluation-context
                #:default-evaluation-context
                #:document-namespace-name
                #:document-namespace-ref
                #:document-namespace-set
                #:document-namespace-function-ref
                #:document-namespace-function-set
                #:evaluation-context-current-document
                #:evaluation-context-current-namespace
                #:evaluation-context-dynamic-frame
                #:evaluation-context-session
                #:find-runtime-session-document
                #:function-cell-function
                #:intern-autolisp-symbol
                #:lookup-function
                #:lookup-variable
                #:make-document-namespace
                #:make-evaluation-context
                #:make-autolisp-string
                #:make-autolisp-subr
                #:make-runtime-session
                #:make-separate-vlx-namespace
                #:namespace-function-cell
                #:namespace-value-cell
                #:pop-dynamic-frame
                #:propagate-variable
                #:push-dynamic-frame
                #:read-runtime-from-string
                #:register-runtime-session-document
                #:reader-object->runtime-value
                #:reset-autolisp-symbol-table
                #:export-function-to-current-document
                #:enter-document-context
                #:import-function-from-current-document
                #:import-functions-from-application
                #:runtime-session-blackboard-namespace
                #:runtime-session-current-document
                #:set-runtime-session-current-document
                #:separate-vlx-namespace-name
                #:set-default-evaluation-context
                #:set-autolisp-errno
                #:set-function
                #:register-runtime-session-vlx-namespace
                #:set-variable
                #:value-cell-value
                #:runtime-value-p)
  (:import-from #:clautolisp.autolisp-reader
                #:read-forms-from-string
                #:read-result-objects)
  (:export #:autolisp-runtime-suite
           #:run-all-tests))
