(defpackage #:clautolisp.autolisp-runtime
  (:use #:cl)
  (:import-from #:clautolisp.autolisp-reader
                #:cons-object
                #:cons-object-dotted-p
                #:cons-object-elements
                #:cons-object-tail
                #:cons-object-span
                #:quote-object-span
                #:cons-object-preceding-doc
                #:integer-object
                #:integer-object-value
                #:quote-object
                #:quote-object-object
                #:real-object
                #:real-object-value
                #:read-forms-from-file
                #:read-forms-from-stream
                #:read-forms-from-string
                #:read-result-objects
                #:string-object
                #:string-object-value
                #:symbol-object
                #:symbol-object-canonical-name)
  (:export
   #:autolisp-string
   #:make-autolisp-string
   #:autolisp-string-value
   #:autolisp-symbol
   #:autolisp-symbol-name
   #:autolisp-symbol-original-name
   #:autolisp-symbol-value
   #:autolisp-symbol-value-bound-p
   #:autolisp-symbol-function
   #:autolisp-symbol-function-bound-p
   #:binding-cell
   #:binding-cell-value
   #:binding-cell-bound-p
   #:binding-cell-compatibility-definition
   #:binding-cell-doc
   #:value-cell
   #:value-cell-value
   #:value-cell-bound-p
   #:function-cell
   #:function-cell-function
   #:function-cell-bound-p
   #:function-cell-compatibility-definition
   #:document-namespace
   #:make-document-namespace
   #:document-namespace-name
   #:blackboard-namespace
   #:make-blackboard-namespace
   #:blackboard-namespace-name
   #:separate-vlx-namespace
   #:make-separate-vlx-namespace
   #:separate-vlx-namespace-name
   #:dynamic-frame
   #:make-dynamic-frame
   #:evaluation-context
   #:make-evaluation-context
   #:evaluation-context-session
   #:evaluation-context-current-document
   #:evaluation-context-current-namespace
   #:evaluation-context-dynamic-frame
   #:runtime-session
   #:make-runtime-session
   #:runtime-session-current-document
   #:runtime-session-blackboard-namespace
   #:runtime-session-errno
   #:find-runtime-session-document
   #:register-runtime-session-document
   #:find-runtime-session-vlx-namespace
   #:register-runtime-session-vlx-namespace
   #:set-runtime-session-current-document
   #:autolisp-file
   #:make-autolisp-file
   #:autolisp-file-stream
   #:autolisp-file-path
   #:autolisp-file-mode
   #:autolisp-ename
   #:autolisp-ename-value
   #:make-autolisp-ename
   #:autolisp-pickset
   #:autolisp-pickset-value
   #:make-autolisp-pickset
   #:autolisp-subr
   #:make-autolisp-subr
   #:autolisp-subr-name
   #:autolisp-subr-function
   #:autolisp-usubr
   #:make-autolisp-usubr
   #:autolisp-usubr-name
   #:autolisp-usubr-lambda-list
   #:autolisp-usubr-body
   #:autolisp-usubr-environment
   #:autolisp-usubr-instrumented-body
   #:autolisp-usubr-debug-metadata
   #:autolisp-catch-all-error
   #:make-autolisp-catch-all-error
   #:autolisp-catch-all-error-message
   #:autolisp-catch-all-error-condition
   #:autolisp-catch-all-error-call-stack
   #:autolisp-runtime-error
   #:autolisp-runtime-error-code
   #:autolisp-runtime-error-call-stack
   #:current-autolisp-call-stack
   #:autolisp-runtime-error-message
   #:autolisp-runtime-error-details
   #:autolisp-termination
   #:autolisp-termination-kind
   #:autolisp-namespace-exit
   #:autolisp-namespace-exit-kind
   #:autolisp-namespace-exit-value
   #:autolisp-variant
   #:autolisp-variant-value
   #:make-autolisp-variant
   #:autolisp-safearray
   #:autolisp-safearray-value
   #:make-autolisp-safearray
   #:autolisp-vla-object
   #:autolisp-vla-object-value
   #:make-autolisp-vla-object
   #:intern-autolisp-symbol
   #:find-autolisp-symbol
   #:reset-autolisp-symbol-table
   #:default-evaluation-context
   #:current-evaluation-context
   #:set-default-evaluation-context
   #:reset-default-evaluation-context
   #:enter-document-context
   #:call-with-autolisp-error-handler
   #:autolisp-errno
   #:autolisp-runtime-error-errno
   #:signal-autolisp-runtime-error
   #:set-autolisp-errno
   #:namespace-binding-cell
   #:namespace-value-cell
   #:namespace-function-cell
   #:document-namespace-ref
   #:document-namespace-set
   #:document-namespace-function-ref
   #:document-namespace-function-set
   #:current-document-namespace-ref
   #:current-document-namespace-set
   #:export-function-to-current-document
   #:import-function-from-current-document
   #:import-functions-from-application
   #:blackboard-ref
   #:blackboard-set
   #:propagate-variable
   #:lookup-variable
   #:set-variable
   #:lookup-function
   #:set-function
   #:lookup-documentation
   #:set-binding-doc
   #:*preceding-docs*
   #:*current-form*
   #:register-preceding-doc
   #:current-form-preceding-doc
   #:push-dynamic-frame
   #:pop-dynamic-frame
   #:bind-dynamic-variable
   #:dynamic-frame-parent
   #:dynamic-frame-symbols
   #:dynamic-frame-binding-value
   #:set-dynamic-frame-binding-value
   #:autolisp-eval
   #:autolisp-eval-progn
   #:autolisp-compiled-eval
   #:autolisp-eval-toplevel-progn
   ;; Debugger integration (clautolisp-debugger).
   #:*debugging*
   #:*instrument-usubr-hook*
   #:*debug-instrumentation-enabled*
   #:*clal-on-error*
   #:register-special-operator
   #:unregister-special-operator
   #:known-special-operator-p
   #:split-usubr-lambda-list
   #:catch-frame
   #:make-catch-frame
   #:catch-frame-function
   #:catch-frame-arguments
   #:*autolisp-catch-stack*
   #:*autolisp-caught-error-hook*
   #:*debug-break-hook*
   #:*debug-define-command-hook*
   #:autolisp-current-directory
   #:set-autolisp-current-directory
   #:autolisp-support-paths
   #:set-autolisp-support-paths
   #:autolisp-trusted-paths
   #:set-autolisp-trusted-paths
   #:autolisp-trusted-init-files
   #:set-autolisp-trusted-init-files
   #:autolisp-true-p
   #:autolisp-false-p
   #:autolisp-boundp
   #:autolisp-null
   #:autolisp-not
   #:autolisp-listp
   #:autolisp-atom
   #:autolisp-type
   #:autolisp-vl-symbolp
   #:autolisp-vl-symbol-name
   #:autolisp-vl-symbol-value
   #:autolisp-function-list-definition
   #:set-autolisp-function-list-definition
   #:set-autolisp-symbol-function
   #:set-autolisp-symbol-value
   #:close-autolisp-file
   #:call-autolisp-function
   #:resolve-autolisp-function-designator
   #:*autolisp-trace-p*
   #:*autolisp-trace-depth*
   #:*autolisp-trace-stream*
   #:*autolisp-traced-symbols*
   #:runtime-value-p
   #:reader-object->runtime-value
   #:reader-objects->runtime-values
   #:autolisp-read-from-string
   #:autolisp-read-from-stream
   #:autolisp-read-from-file
   #:autolisp-load-file
   #:autolisp-load-file-in-context
   #:read-runtime-from-string
   #:read-runtime-from-stream
   #:read-runtime-from-file
   #:runtime-session-dialect
   #:set-runtime-session-dialect
   #:runtime-session-host
   #:set-runtime-session-host
   #:current-evaluation-host
   #:*default-runtime-host*
   #:current-evaluation-dialect
   #:derive-reader-options-for-dialect
   #:make-default-runtime-context
   #:run-autolisp-file
   #:run-autolisp-string
   ;; Phase 14a — host-object ontology + event channel
   #:reactor
   #:make-reactor
   #:reactor-id
   #:reactor-kind
   #:reactor-scope
   #:reactor-callbacks
   #:reactor-owners
   #:reactor-data
   #:reactor-active-p
   #:reactor-persistent-p
   #:reactor-notification
   #:reactor-document
   #:*reactor-type-table*
   #:reactor-type-scope
   #:reactor-type-name
   #:reactor-type-keywords
   #:document-reactor-registry
   #:session-reactor-registry
   #:add-reactor-to-document
   #:add-reactor-to-session
   #:remove-reactor-from-document
   #:remove-reactor-from-session
   #:all-document-reactors
   #:all-application-reactors
   #:all-session-reactors
   #:signal-document-event
   #:signal-application-event
   #:set-document-state
   #:set-application-state
   #:document-namespace-state
   #:runtime-session-application-state
   #:document-namespace-persistent-reactor-index
   #:runtime-session-event-trace
   #:set-runtime-session-event-trace
   #:call-with-event-trace
   ;; Source-file encoding override (set by the CLI's -e flag).
   #:runtime-session-default-source-encoding
   #:set-runtime-session-default-source-encoding
   #:set-default-source-encoding
   ;; POSIX locale probe (LC_ALL / LC_CTYPE / LANG).
   #:locale-default-source-encoding
   #:parse-posix-locale
   #:parse-locale-encoding-string
   #:lookup-autolisp-file-encoding
   ;; Encoding-dispatch diagnostics (encoding-dispatch.issue Phase 4).
   #:*enc-diagnostic-stream*
   #:*enc-diagnostic-suppress-p*
   #:*enc-diagnostic-suppress-codes*
   #:*enc-diagnostic-codes*
   #:signal-encoding-diagnostic
   #:call-with-suppressed-encoding-diagnostics
   #:*secureload-diagnostic-stream*
   #:*secureload-diagnostic-suppress-p*
   #:*secureload-diagnostic-codes*
   #:signal-secureload-diagnostic
   ;; Terminal colour-output policy. *COLOR-OUTPUT* is the single
   ;; switch the AUTOLISP-SYMBOL PRINT-OBJECT method consults; the
   ;; CLI calls RESOLVE-COLOR-POLICY at startup, binds the result
   ;; for the run, and library code below never touches it.
   #:*color-output*
   #:ansi-colorize
   #:write-ansi-colorized
   #:env-no-color-set-p
   #:parse-colorfgbg
   #:parse-colour-name
   #:env-symbol-foreground
   #:env-symbol-background
   #:env-symbol-colour-spec
   #:parse-osc11-response
   #:luminance-of-rgb
   #:terminal-background-luminance
   #:output-stream-is-tty-p
   #:resolve-color-policy))

(defpackage #:clautolisp.autolisp-runtime.internal
  (:use #:cl)
  (:export
   #:*autolisp-symbol-table*
   #:autolisp-ename
   #:autolisp-file
   #:autolisp-pickset
   #:autolisp-safearray
   #:autolisp-string
   #:autolisp-subr
   #:autolisp-symbol
   #:autolisp-usubr
   #:autolisp-catch-all-error
   #:autolisp-variant
   #:autolisp-vla-object
   #:make-autolisp-ename
   #:make-autolisp-file
   #:make-autolisp-pickset
   #:make-autolisp-safearray
   #:make-autolisp-string
   #:make-autolisp-subr
   #:make-autolisp-symbol
   #:make-blackboard-namespace
   #:make-document-namespace
   #:make-dynamic-binding
   #:make-dynamic-frame
   #:make-evaluation-context
   #:make-binding-cell
   #:make-runtime-session
   #:make-separate-vlx-namespace
   #:make-autolisp-usubr
   #:make-autolisp-catch-all-error
   #:make-autolisp-variant
   #:make-autolisp-vla-object
   #:*active-evaluation-context*))
