(defpackage #:clautolisp.autolisp-runtime
  (:use #:cl)
  (:import-from #:clautolisp.autolisp-reader
                #:cons-object
                #:cons-object-dotted-p
                #:cons-object-elements
                #:cons-object-tail
                #:integer-object
                #:integer-object-value
                #:quote-object
                #:quote-object-object
                #:real-object
                #:real-object-value
                #:read-forms-from-file
                #:read-forms-from-stream
                #:read-forms-from-string
                #:read-result-objects
                #:string-object
                #:string-object-value
                #:symbol-object
                #:symbol-object-canonical-name)
  (:export
   #:autolisp-string
   #:make-autolisp-string
   #:autolisp-string-value
   #:autolisp-symbol
   #:autolisp-symbol-name
   #:autolisp-symbol-original-name
   #:autolisp-symbol-value
   #:autolisp-symbol-value-bound-p
   #:autolisp-symbol-function
   #:autolisp-symbol-function-bound-p
   #:value-cell
   #:value-cell-value
   #:value-cell-bound-p
   #:function-cell
   #:function-cell-function
   #:function-cell-bound-p
   #:function-cell-compatibility-definition
   #:document-namespace
   #:make-document-namespace
   #:document-namespace-name
   #:blackboard-namespace
   #:make-blackboard-namespace
   #:blackboard-namespace-name
   #:separate-vlx-namespace
   #:make-separate-vlx-namespace
   #:separate-vlx-namespace-name
   #:dynamic-frame
   #:make-dynamic-frame
   #:evaluation-context
   #:make-evaluation-context
   #:evaluation-context-session
   #:evaluation-context-current-document
   #:evaluation-context-current-namespace
   #:evaluation-context-dynamic-frame
   #:runtime-session
   #:make-runtime-session
   #:runtime-session-current-document
   #:set-runtime-session-current-document
   #:autolisp-file
   #:make-autolisp-file
   #:autolisp-file-stream
   #:autolisp-file-path
   #:autolisp-file-mode
   #:autolisp-ename
   #:autolisp-ename-value
   #:autolisp-pickset
   #:autolisp-pickset-value
   #:autolisp-subr
   #:make-autolisp-subr
   #:autolisp-subr-name
   #:autolisp-subr-function
   #:autolisp-usubr
   #:make-autolisp-usubr
   #:autolisp-usubr-name
   #:autolisp-usubr-lambda-list
   #:autolisp-usubr-body
   #:autolisp-usubr-environment
   #:autolisp-catch-all-error
   #:make-autolisp-catch-all-error
   #:autolisp-catch-all-error-message
   #:autolisp-catch-all-error-condition
   #:autolisp-runtime-error
   #:autolisp-runtime-error-code
   #:autolisp-runtime-error-message
   #:autolisp-runtime-error-details
   #:autolisp-variant
   #:autolisp-variant-value
   #:autolisp-safearray
   #:autolisp-safearray-value
   #:autolisp-vla-object
   #:autolisp-vla-object-value
   #:intern-autolisp-symbol
   #:find-autolisp-symbol
   #:reset-autolisp-symbol-table
   #:default-evaluation-context
   #:set-default-evaluation-context
   #:reset-default-evaluation-context
   #:enter-document-context
   #:call-with-autolisp-error-handler
   #:namespace-value-cell
   #:namespace-function-cell
   #:lookup-variable
   #:set-variable
   #:lookup-function
   #:set-function
   #:push-dynamic-frame
   #:pop-dynamic-frame
   #:bind-dynamic-variable
   #:autolisp-eval
   #:autolisp-eval-progn
   #:autolisp-current-directory
   #:set-autolisp-current-directory
   #:autolisp-support-paths
   #:set-autolisp-support-paths
   #:autolisp-trusted-paths
   #:set-autolisp-trusted-paths
   #:autolisp-true-p
   #:autolisp-false-p
   #:autolisp-boundp
   #:autolisp-null
   #:autolisp-not
   #:autolisp-listp
   #:autolisp-atom
   #:autolisp-type
   #:autolisp-vl-symbolp
   #:autolisp-vl-symbol-name
   #:autolisp-vl-symbol-value
   #:autolisp-function-list-definition
   #:set-autolisp-function-list-definition
   #:set-autolisp-symbol-function
   #:set-autolisp-symbol-value
   #:close-autolisp-file
   #:call-autolisp-function
   #:resolve-autolisp-function-designator
   #:runtime-value-p
   #:reader-object->runtime-value
   #:reader-objects->runtime-values
   #:autolisp-read-from-string
   #:autolisp-read-from-stream
   #:autolisp-read-from-file
   #:autolisp-load-file
   #:autolisp-load-file-in-context
   #:read-runtime-from-string
   #:read-runtime-from-stream
   #:read-runtime-from-file))

(defpackage #:clautolisp.autolisp-runtime.internal
  (:use #:cl)
  (:export
   #:*autolisp-symbol-table*
   #:autolisp-ename
   #:autolisp-file
   #:autolisp-pickset
   #:autolisp-safearray
   #:autolisp-string
   #:autolisp-subr
   #:autolisp-symbol
   #:autolisp-usubr
   #:autolisp-catch-all-error
   #:autolisp-variant
   #:autolisp-vla-object
   #:make-autolisp-ename
   #:make-autolisp-file
   #:make-autolisp-pickset
   #:make-autolisp-safearray
   #:make-autolisp-string
   #:make-autolisp-subr
   #:make-autolisp-symbol
   #:make-blackboard-namespace
   #:make-document-namespace
   #:make-dynamic-binding
   #:make-dynamic-frame
   #:make-evaluation-context
   #:make-function-cell
   #:make-runtime-session
   #:make-separate-vlx-namespace
   #:make-value-cell
   #:make-autolisp-usubr
   #:make-autolisp-catch-all-error
   #:make-autolisp-variant
   #:make-autolisp-vla-object))
