(in-package #:clautolisp.autolisp-mock-host)

;;;; BricsCAD-dialect sysvar overlay.
;;;;
;;;; The mock host's sysvar catalogue (sysvar-catalogue.lisp) is
;;;; generated from the AutoCAD-2026 system-variables inventory, so by
;;;; default `clautolisp --bricscad` reports the *AutoCAD* sysvar set —
;;;; every dialect answers GETVAR identically (see
;;;; issues/open/bricscad-dialect-sysvar-parity.issue). This overlay
;;;; specialises the table for the bricscad dialect at launch time.
;;;;
;;;; Phase 1 (this file) covers *existence* only: the variables BricsCAD
;;;; does not define are dropped from the table, so GETVAR returns nil and
;;;; SETVAR signals unknown-sysvar — matching a real BricsCAD. Existence
;;;; is locale-, profile-, platform- and drawing-independent, so it is the
;;;; one class we can adopt unconditionally from a single probe.
;;;;
;;;; NOT touched here, by design:
;;;;   - engine identity (PROGRAM / VENDORNAME / PLATFORM / ACADVER /
;;;;     PRODUCT) — clautolisp keeps its own identity, stamped by
;;;;     APPLY-CLAUTOLISP-HOST-IDENTITY;
;;;;   - dynamic state (SYSCODEPAGE / DWGCODEPAGE / DATE / CDATE /
;;;;     MILLISECS / ERRNO …) — already computed live;
;;;;   - the genuine static *value* differences (factory defaults that
;;;;     BricsCAD and AutoCAD set differently) — deferred until they can
;;;;     be re-harvested from a *pristine* BricsCAD profile rather than a
;;;;     customised session. The data shape below already accommodates
;;;;     them (a :VALUE override), so Phase 2 only adds rows.
;;;;
;;;; Provenance of *BRICSCAD-ABSENT-SYSVARS*
;;;; ---------------------------------------
;;;; The 382 names below are the INTERSECTION of two independent sources:
;;;;   (a) the inventory's per-variable  :versions (… :bricscad nil)
;;;;       marker (autolisp-spec/.../system-variables-inventory.sexp);
;;;;   (b) a live `alfe --bricscad` probe of BricsCAD V26 on macOS that
;;;;       returned nil for the variable
;;;;       (sysvars-alfe-Darwin-bricscad.txt).
;;;; Requiring agreement keeps out the 39 inventory rows the V26 probe
;;;; contradicts (e.g. 3DOSMODE, BPARAMETERFONT — BricsCAD *does* define
;;;; them; the inventory marker is stale) and the 98 probe-nil rows the
;;;; inventory still lists for BricsCAD (edition-/platform-specific
;;;; absences we must not assume hold on every BricsCAD build). Both
;;;; residues are tracked in the issue.

(defparameter *bricscad-absent-sysvars*
  '(
    "3DCONVERSIONMODE" "3DDWFPREC" "3DSELECTIONMODE"
    "ACTIVITYINSIGHTSPATH" "ACTIVITYINSIGHTSSTATE" "ACTIVITYINSIGHTSSUPPORT"
    "ACTIVITYINSIGHTSVIEWEDLOGGING" "ACTPATH" "ACTRECORDERSTATE"
    "ACTRECPATH" "ACTUI" "ADCSTATE"
    "ANNOSCALEZOOM" "APPAUTOLOAD" "APPLYGLOBALOPACITIES"
    "APSTATE" "ASSISTANTSTATE" "ATTIPE"
    "ATTMULTI" "AUTODWFPUBLISH" "AUTOMATICPUB"
    "AUTOPLACEMENT" "BCONSTATUSMODE" "BCONVERTLAYER"
    "BGCOREPUBLISH" "BLOCKCREATEMODE" "BLOCKEXCLUDECOLOR"
    "BLOCKINCLUDECOLOR" "BLOCKMRULIST" "BLOCKNAVIGATE"
    "BLOCKREDEFINEMODE" "BLOCKSDATACOLLECTION" "BLOCKSRECENTFOLDER"
    "BLOCKSTATE" "BLOCKSYNCFOLDER" "BLOCKTARGETCOLOR"
    "BSEARCHINCLUDEEXISTINGBLOCKS" "CACHEMAXFILES" "CACHEMAXTOTALSIZE"
    "CALCINPUT" "CAPTURETHUMBNAILS" "CBARTRANSPARENCY"
    "CCONSTRAINTFORM" "CLAYOUT" "CMDINPUTHISTORYMAX"
    "CMFADECOLOR" "CMFADEOPACITY" "CMOSNAP"
    "COMMANDMACROSSTATE" "COMMENTHIGHLIGHT" "COMPARECOLOR1"
    "COMPARECOLOR2" "COMPARECOLORCOMMON" "COMPAREFRONT"
    "COMPAREHATCH" "COMPAREPROPS" "COMPARERCMARGIN"
    "COMPARERCSHAPE" "COMPARESHOW1" "COMPARESHOW2"
    "COMPARESHOWCOMMON" "COMPARESHOWCONTEXT" "COMPARESHOWRC"
    "COMPARETEXT" "COMPARETOLERANCE" "COMPLEXLTPREVIEW"
    "CONSTRAINTBARMODE" "CONSTRAINTINFER" "CONSTRAINTNAMEFORMAT"
    "CONSTRAINTSOLVEMODE" "COUNTCHECK" "COUNTCOLOR"
    "COUNTERRORCOLOR" "COUNTERRORNUM" "COUNTNUMBER"
    "COUNTPALETTESTATE" "COUNTSERVICE" "CULLINGOBJ"
    "CULLINGOBJSELECTION" "CURSORBADGE" "CURSORTYPE"
    "CVIEWDETAILSTYLE" "DEFAULTGIZMO" "DEFAULTLIGHTINGTYPE"
    "DGNIMPORTMAX" "DGNIMPORTMODE" "DGNMAPPINGPATH"
    "DIMCONSTRAINTICON" "DIMPICKBOX" "DIMTXTRULER"
    "DISPSILHBLOCKS" "DIVMESHBOXHEIGHT" "DIVMESHBOXLENGTH"
    "DIVMESHBOXWIDTH" "DIVMESHCONEAXIS" "DIVMESHCONEBASE"
    "DIVMESHCONEHEIGHT" "DIVMESHCYLAXIS" "DIVMESHCYLBASE"
    "DIVMESHCYLHEIGHT" "DIVMESHPYRBASE" "DIVMESHPYRHEIGHT"
    "DIVMESHPYRLENGTH" "DIVMESHSPHEREAXIS" "DIVMESHSPHEREHEIGHT"
    "DIVMESHTORUSPATH" "DIVMESHTORUSSECTION" "DIVMESHWEDGEBASE"
    "DIVMESHWEDGEHEIGHT" "DIVMESHWEDGELENGTH" "DIVMESHWEDGESLOPE"
    "DIVMESHWEDGEWIDTH" "DRAGVS" "DRSTATE"
    "DX12FRAMERATEUNLIMITED" "DYNPIFORMAT" "DYNPIVIS"
    "DYNPROMPT" "DYNTOOLTIPS" "ENABLESYNCPDF"
    "ENTERPRISEMENU" "ERHIGHLIGHT" "ERSTATE"
    "EXPORTEPLOTFORMAT" "EXPVALUE" "EXPWHITEBALANCE"
    "FACETERDEVNORMAL" "FACETERDEVSURFACE" "FACETERMAXEDGELENGTH"
    "FACETERMAXGRID" "FACETERMESHTYPE" "FACETERMINVGRID"
    "FACETERPRIMITIVEMODE" "FACETERSMOOTHLEV" "FASTSHADEDMODE"
    "FILETABPREVIEW" "FILETABSTATE" "FILETABTHUMBHOVER"
    "FILLETPOLYARC" "FULLPLOTPATH" "GALLERYVIEW"
    "GEOLOCATEMODE" "GEOMARKPOSITIONSIZE" "GLOBALOPACITY"
    "GRIPCONTOUR" "GRIPSUBOBJMODE" "GTAUTO"
    "GTDEFAULT" "GTLOCATION" "HELPPREFIX"
    "HPDLGMODE" "HPDRAWMODE" "HPISLANDDETECTIONMODE"
    "HPPATHALIGNMENT" "HPPATHWIDTH" "HPPICKMODE"
    "HPQUICKPREVTIMEOUT" "IBLENVIRONMENT" "IMAGEASYNC"
    "IMPLIEDFACE" "INPUTHISTORYMODE" "INTELLIGENTUPDATE"
    "JIGZOOMMAX" "JIGZOOMMIN" "LARGEOBJECTSUPPORT"
    "LAYERDLGMODE" "LAYEREVAL" "LAYERFILTERALERT"
    "LAYERMANAGERSTATE" "LAYERNOTIFY" "LAYEROVERRIDEHIGHLIGHT"
    "LAYOUTCREATEVIEWPORT" "LEGACYCTRLPICK" "LIGHTSINBLOCKS"
    "LINEFADING" "LINEFADINGLEVEL" "MACROINSIGHTSSUPPORT"
    "MACRONOTIFY" "MARKUPASSISTMODE" "MARKUPPAPERDISPLAY"
    "MARKUPPAPERTRANSPARENCY" "MARKUPSELECTIONMODE" "MATBROWSERSTATE"
    "MATEDITORSTATE" "MAXINTERSECTIONCURVEPOINTS" "MLEADERLAYER"
    "MSMSTATE" "MTEXTEDENCODING" "MTJIGSTRING"
    "MVIEWPREVIEW" "NAVSWHEELMODE" "NAVSWHEELOPACITYBIG"
    "NAVSWHEELOPACITYMINI" "NAVSWHEELSIZEBIG" "NAVSWHEELSIZEMINI"
    "NAVVCUBESIZE" "OSNAPNODELEGACY" "OSNAPOVERRIDE"
    "PALETTEOPAQUE" "PARAMETERSSTATUS" "PASTESPECMODE"
    "PCMSTATE" "PDFIMPORTFILTER" "PDFIMPORTLAYERS"
    "PDFIMPORTMODE" "PDFSHXBESTFONT" "PDFSHXLAYER"
    "PDFSHXTHRESHOLD" "PERSPECTIVECLIP" "PLACEMENTSWITCH"
    "PLINEGCENMAX" "PLOTOFFSET" "POINTCLOUDAUTOUPDATE"
    "POINTCLOUDCACHESIZE" "POINTCLOUDCLIPFRAME" "POINTCLOUDDENSITY"
    "POINTCLOUDLIGHTING" "POINTCLOUDLIGHTSOURCE" "POINTCLOUDLOCK"
    "POINTCLOUDLOD" "POINTCLOUDPOINTMAXLEGACY" "POINTCLOUDRTDENSITY"
    "POINTCLOUDSHADING" "POINTCLOUDVISRETAIN" "PREVIEWCREATIONTRANSPARENCY"
    "PROJECTAWARE" "PUBLISHHATCH" "PUSHTODOCSSTATE"
    "QCSTATE" "QPLOCATION" "QPMODE"
    "QVDRAWINGPIN" "QVLAYOUTPIN" "RASTERDPI"
    "RASTERPERCENT" "RASTERTHRESHOLD" "REBUILD2DCV"
    "REBUILD2DDEGREE" "REBUILD2DOPTION" "REBUILDDEGREEU"
    "REBUILDDEGREEV" "REBUILDOPTIONS" "REBUILDU"
    "REBUILDV" "RECOVERAUTO" "RECOVERYMODE"
    "RENDERENVSTATE" "RENDERLEVEL" "RENDERLIGHTCALC"
    "RENDERPREFSSTATE" "RENDERTARGET" "RENDERTIME"
    "RENDERUSERLIGHTS" "REPORTERROR" "REVCLOUDAPPROXARCLEN"
    "REVCLOUDARCVARIANCE" "REVCLOUDLAYER" "REVCLOUDSCALEMODE"
    "RIBBONBGLOAD" "RIBBONCONTEXTSELLIM" "RIBBONICONRESIZE"
    "RTREGENAUTO" "SECTIONOFFSETINC" "SECTIONTHICKNESSINC"
    "SECUREREMOTEACCESS" "SELECTIONEFFECT" "SELECTIONEFFECTCOLOR"
    "SELECTIONOFFSCREEN" "SELECTIONPREVIEWLIMIT" "SHAREDVIEWSTATE"
    "SHAREVIEWPROPERTIES" "SHAREVIEWTYPE" "SHOWHIST"
    "SHOWNEWSTATE" "SHOWPALETTESTATE" "SMOOTHMESHGRID"
    "SMOOTHMESHMAXFACE" "SMOOTHMESHMAXLEV" "SNAPGRIDLEGACY"
    "SOLIDHIST" "SORTORDER" "SPACESWITCH"
    "SPLDEGREE" "SPLKNOTS" "SPLMETHOD"
    "SPLPERIODIC" "SSMOPENMODE" "STARTINFOLDER"
    "STUDENTDRAWING" "STYLUSFORCETHRESHOLD" "SUBOBJSELECTIONMODE"
    "SUNPROPERTIESSTATE" "SURFACEASSOCIATIVITY" "SURFACEASSOCIATIVITYDRAG"
    "SURFACEAUTOTRIM" "SURFACEMODELINGMODE" "SYSFLOATING"
    "SYSMON" "TABLEINDICATOR" "TABLELAYER"
    "TABLETOOLBAR" "TBCUSTOMIZE" "TBSHOWSHORTCUTS"
    "TEMPOVERRIDES" "TEXTALIGNMODE" "TEXTALIGNSPACING"
    "TEXTALLCAPS" "TEXTAUTOCORRECTCAPS" "TEXTGAPSELECTION"
    "TEXTJUSTIFY" "TEXTLAYER" "TEXTOUTPUTFILEFORMAT"
    "TEXTTOATTRIBUTE" "THUMBSAVE" "THUMBSIZE2D"
    "TOOLTIPMERGE" "TOOLTIPTRANSPARENCY" "TOUCHMODE"
    "TRACECURRENT" "TRACEDISPLAYMODE" "TRACEFADECTL"
    "TRACEMARKUPFADECTL" "TRACEMODE" "TRACEOSNAP"
    "TRACEPALETTESTATE" "TRACEPAPERCTL" "TRACEVPSUPPORT"
    "UCS2DDISPLAYSETTING" "UCS3DPARADISPLAYSETTING" "UCS3DPERPDISPLAYSETTING"
    "UCSSELECTMODE" "UOSNAP" "UPDATETHUMBNAIL"
    "VIEWBACKSTATUS" "VIEWFWDSTATUS" "VIEWPORTLAYER"
    "VIEWSKETCHMODE" "VISRETAINMODE" "VPCONTROL"
    "VPLAYEROVERRIDES" "VSACURVATUREHIGH" "VSACURVATURELOW"
    "VSACURVATURETYPE" "VSADRAFTANGLEHIGH" "VSAZEBRACOLOR1"
    "VSAZEBRACOLOR2" "VSAZEBRADIRECTION" "VSAZEBRASIZE"
    "VSAZEBRATYPE" "VSBACKGROUNDS" "VSEDGECOLOR"
    "VSEDGEJITTER" "VSEDGELEX" "VSEDGES"
    "VSEDGESMOOTH" "VSFACECOLORMODE" "VSFACEHIGHLIGHT"
    "VSFACEOPACITY" "VSHALOGAP" "VSINTERSECTIONCOLOR"
    "VSINTERSECTIONEDGES" "VSINTERSECTIONLTYPE" "VSISOONTOP"
    "VSLIGHTINGQUALITY" "VSMATERIALMODE" "VSMONOCOLOR"
    "VSOCCLUDEDCOLOR" "VSOCCLUDEDEDGES" "VSOCCLUDEDLTYPE"
    "VSSHADOWS" "VSSILHEDGES" "VSSILHWIDTH"
    "VSSTATE" "WBLOCKCREATEMODE" "WORKINGFOLDER"
    "WORKSPACELABEL" "XCOMPAREBAKPATH" "XCOMPAREBAKSIZE"
    "XCOMPARECOLORMODE" "XCOMPAREENABLE" "XREFLAYER"
    "XREFREGAPPCTL")
  "The 382 catalogue sysvars BricsCAD V26 does not define, confirmed by
both the inventory's :bricscad version marker and a live BricsCAD V26
probe. Dropped from the host table under the bricscad dialect so GETVAR
returns nil. See the file header for provenance.")

(defun apply-bricscad-dialect-sysvars (host)
  "Launch-time bricscad-dialect sysvar overlay (Phase 1): drop the
catalogue entries BricsCAD does not define from HOST, so GETVAR on them
returns nil and SETVAR signals unknown-sysvar, as on a real BricsCAD.
Mock-host only; no-ops on hosts without a sysvar table. Returns HOST."
  (when host
    (dolist (name *bricscad-absent-sysvars*)
      (clautolisp.autolisp-host:host-undefine-sysvar host name)))
  host)
