;;;; cadtui -- CAD command option-keyword dictionary (:option-keyword).
;;;; GENERATED by scripts/cadtui-optkw-to-sexp.py --pair probe-results/optkw/fr_FR/international-en.json
;;;; -- do not hand-edit; fix the pairing table or the harvest and re-run.
;;;; Per PRODUCT (the two vendors' keyword sets differ), per international
;;;; command: (international-keyword . local-keyword). The local keyword is
;;;; as the French prompt shows it; its capitals are its abbreviation.
;;;; International side: the vendor's English command reference (url per
;;;; command below), paired by position and meaning -- not a measured
;;;; English prompt. Missing => the international keyword (fallback).
;;;; Left to measure on an English install (not settled by the docs):
;;;;   bricscad _BREAK sélectionner les options (?)
;;;;   bricscad _CHAMFER sélectionner les options (?)
;;;;   bricscad _EXTEND sélectionner les options (?)
;;;;   bricscad _FILLET sélectionner les options (?)
;;;;   bricscad _MIRROR sélectionner les options (?)
;;;;   bricscad _ROTATE sélectionner les options (?)
;;;;   bricscad _SCALE sélectionner les options (?)
;;;;   bricscad _TRIM sélectionner les options (?)
(
 (:AUTOCAD
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-B1DCF991-90A7-4DB0-96FC-BDA3FB76337C.htm
  ("_CHAMFER" ("Undo" . "aNnuler") ("Polyline" . "Polyligne") ("Distance" . "Ecart") ("Angle" . "ANgle") ("Trim" . "AJuster") ("Method" . "Méthode") ("Multiple" . "mUltiple"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-89DD7B0F-F4F1-410D-9A3A-5847CA5F8744.htm
  ("_EXTEND" ("Mode" . "mOde"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-64F8B700-23B3-4BD6-8C03-66121AA13E8F.htm
  ("_FILLET" ("Undo" . "aNnuler") ("Polyline" . "Polyligne") ("Radius" . "Rayon") ("Trim" . "Ajuster") ("Multiple" . "mUltiple"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-76C74C62-DBAA-41E7-8422-F0EE7E769638.htm
  ("_LENGTHEN" ("Delta" . "DIfférence") ("Percent" . "Pourcentage") ("Total" . "TOtal") ("Dynamic" . "DYnamique"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-C0E4246D-C420-42BD-A6FC-8B1852EFD005.htm
  ("_OFFSET" ("Through" . "Par") ("Erase" . "Effacer") ("Layer" . "Calque"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-188B2DDA-6CD8-4D37-BF26-E6CF27C34C75.htm
  ("_RECTANG" ("Chamfer" . "Chanfrein") ("Elevation" . "Elévation") ("Fillet" . "Raccord") ("Thickness" . "Hauteur") ("Width" . "Largeur"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-B1A185EF-07C6-4C53-A76F-05ADE11F5C32.htm
  ("_TRIM" ("Mode" . "mOde"))
  ;; https://help.autodesk.com/cloudhelp/2022/ENU/AutoCAD-Core/files/GUID-66E7DB72-B2A7-4166-9970-9E19CC06F739.htm
  ("_ZOOM" ("All" . "Tout") ("Center" . "Centre") ("Dynamic" . "DYnamique") ("Extents" . "ETendu") ("Previous" . "Précédent") ("Scale" . "Echelle") ("Window" . "Fenêtre") ("Object" . "Objet")))
 (:BRICSCAD
  ;; https://help.bricsys.com/en-us/document/command-reference/c/chamfer-command?version=V25
  ("_CHAMFER" ("chamfer Settings" . "PAramètres du chanfrein...") ("Polyline" . "POlyligne") ("Angle" . "ANgle") ("Distance" . "Distance") ("mEthod" . "méthodE") ("Trim" . "AJuster") ("Undo" . "annUler") ("Multiple" . "Multiple"))
  ;; https://help.bricsys.com/en-us/document/command-reference/e/extend-command?version=V25
  ("_EXTEND" ("mOde" . "Mode"))
  ;; https://help.bricsys.com/en-us/document/command-reference/f/fillet-command?version=V25
  ("_FILLET" ("fillet Settings" . "PAramètres raccord...") ("Polyline" . "Polyligne") ("Radius" . "Rayon") ("Trim" . "Ajuster") ("Undo" . "annUler") ("Multiple" . "Multiple"))
  ;; https://help.bricsys.com/en-us/document/command-reference/l/lengthen-command?version=V25
  ("_LENGTHEN" ("DYnamic" . "DYnamique") ("Increment" . "Incrément") ("Percent" . "Pourcentage") ("Total" . "Total"))
  ;; https://help.bricsys.com/en-us/document/command-reference/o/offset-command?version=V25
  ("_OFFSET" ("Through point" . "Passer par le point") ("Erase" . "Effacer") ("Layer" . "Calque"))
  ;; https://help.bricsys.com/en-us/document/command-reference/r/rectang-command?version=V25
  ("_RECTANG" ("Chamfer" . "Chanfrein") ("Fillet" . "Raccord") ("Rotated" . "Pivoté") ("Square" . "CArré") ("Elevation" . "Elévation") ("Thickness" . "EPaisseur") ("Width of line" . "Largeur de ligne") ("Area" . "Aire") ("Dimensions" . "Dimensions"))
  ;; https://help.bricsys.com/en-us/document/command-reference/t/trim-command?version=V25
  ("_TRIM" ("mOde" . "Mode"))
  ;; https://help.bricsys.com/en-us/document/command-reference/z/zoom-command?version=V25
  ("_ZOOM" ("In" . "zoom Avant") ("Out" . "zoom aRrière") ("All" . "TOUt") ("Center" . "Centre") ("Dynamic" . "DYnamique") ("Extents" . "étendu (ET)") ("Left" . "Gauche") ("Previous" . "Précédent") ("Right" . "Droite") ("Scale" . "Échelle (nx/nxp)") ("Window" . "Fenêtre") ("ENtity" . "ENtité")))
)
