(in-package #:clautolisp.autolisp-builtins-core.tests)

(in-suite autolisp-builtins-core-suite)

(test builtin-registry-returns-subrs
  (let ((builtin (find-core-builtin "TYPE")))
    (is (typep builtin 'autolisp-subr))
    (is (string= "TYPE" (autolisp-subr-name builtin)))))

(test installed-builtins-bind-functions-on-symbols
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let ((symbol (find-autolisp-symbol "TYPE")))
    (is (typep symbol 'autolisp-symbol))
    (is (typep (autolisp-symbol-function symbol) 'autolisp-subr))))

(test builtin-type-call
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((symbol (find-autolisp-symbol "TYPE"))
         (result (call-autolisp-function (autolisp-symbol-function symbol) 42)))
    (is (typep result 'autolisp-symbol))
    (is (string= "INT" (autolisp-symbol-name result)))))

(test builtin-basic-arithmetic
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((+-fn (autolisp-symbol-function (find-autolisp-symbol "+")))
         (--fn (autolisp-symbol-function (find-autolisp-symbol "-")))
         (*-fn (autolisp-symbol-function (find-autolisp-symbol "*")))
         (/-fn (autolisp-symbol-function (find-autolisp-symbol "/")))
         (1+-fn (autolisp-symbol-function (find-autolisp-symbol "1+")))
         (1--fn (autolisp-symbol-function (find-autolisp-symbol "1-")))
         (max-fn (autolisp-symbol-function (find-autolisp-symbol "MAX")))
         (min-fn (autolisp-symbol-function (find-autolisp-symbol "MIN")))
         (rem-fn (autolisp-symbol-function (find-autolisp-symbol "REM")))
         (gcd-fn (autolisp-symbol-function (find-autolisp-symbol "GCD")))
         (lcm-fn (autolisp-symbol-function (find-autolisp-symbol "LCM")))
         (~-fn (autolisp-symbol-function (find-autolisp-symbol "~")))
         (logand-fn (autolisp-symbol-function (find-autolisp-symbol "LOGAND")))
         (logior-fn (autolisp-symbol-function (find-autolisp-symbol "LOGIOR")))
         (lsh-fn (autolisp-symbol-function (find-autolisp-symbol "LSH"))))
    (is (= 0 (call-autolisp-function +-fn)))
    (is (= 6 (call-autolisp-function +-fn 1 2 3)))
    (is (= 1 (call-autolisp-function *-fn)))
    (is (= 24 (call-autolisp-function *-fn 2 3 4)))
    (is (= -7 (call-autolisp-function --fn 7)))
    (is (= 5 (call-autolisp-function --fn 10 2 3)))
    (is (= 0.5d0 (call-autolisp-function /-fn 2)))
    (is (= 5 (call-autolisp-function /-fn 20 2 2)))
    (is (typep (call-autolisp-function /-fn 2) 'double-float))
    (is (typep (call-autolisp-function /-fn 20 2 2) '(signed-byte 32)))
    (is (= 8 (call-autolisp-function 1+-fn 7)))
    (is (= 6 (call-autolisp-function 1--fn 7)))
    (is (= 9 (call-autolisp-function max-fn 1 9 3 7)))
    (is (= 1 (call-autolisp-function min-fn 1 9 3 7)))
    (is (= 2.5d0 (call-autolisp-function max-fn 1 2.5d0 2)))
    (is (= 1.5d0 (call-autolisp-function min-fn 3 1.5d0 2)))
    (is (= 2 (call-autolisp-function rem-fn 17 5)))
    (is (= 4 (call-autolisp-function gcd-fn 20 12)))
    (is (= 6 (call-autolisp-function gcd-fn 54 24 18)))
    (is (= 0 (call-autolisp-function gcd-fn)))
    (is (= 12 (call-autolisp-function lcm-fn 3 4)))
    (is (= 0 (call-autolisp-function lcm-fn 0 5)))
    (is (= 1 (call-autolisp-function lcm-fn)))
    (is (= -1 (call-autolisp-function ~-fn 0)))
    (is (= 2 (call-autolisp-function logand-fn 6 3)))
    (is (= 7 (call-autolisp-function logior-fn 6 3 5)))
    (is (= 20 (call-autolisp-function lsh-fn 5 2)))
    (is (= 1 (call-autolisp-function lsh-fn 4 -2)))))

(test builtin-null-and-not
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((null-fn (autolisp-symbol-function (find-autolisp-symbol "NULL")))
         (not-fn (autolisp-symbol-function (find-autolisp-symbol "NOT"))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function null-fn nil))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function not-fn nil))))
    (is (null (call-autolisp-function null-fn 1)))))

(test builtin-vl-symbol-name
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((foo (intern-autolisp-symbol "FOO"))
         (fn (autolisp-symbol-function (find-autolisp-symbol "VL-SYMBOL-NAME")))
         (result (call-autolisp-function fn foo)))
    (is (typep result 'autolisp-string))
    (is (string= "FOO" (autolisp-string-value result)))))

(test builtin-boundp
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((foo (intern-autolisp-symbol "FOO"))
         (bar (intern-autolisp-symbol "BAR"))
         (fn (autolisp-symbol-function (find-autolisp-symbol "BOUNDP"))))
    (set-autolisp-symbol-value foo 17)
    (set-autolisp-symbol-value bar nil)
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function fn foo))))
    (is (null (call-autolisp-function fn bar)))))

(test builtin-car-cdr-cons-list
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((car-fn (autolisp-symbol-function (find-autolisp-symbol "CAR")))
         (cdr-fn (autolisp-symbol-function (find-autolisp-symbol "CDR")))
         (cons-fn (autolisp-symbol-function (find-autolisp-symbol "CONS")))
         (list-fn (autolisp-symbol-function (find-autolisp-symbol "LIST"))))
    (is (eql 1 (call-autolisp-function car-fn '(1 2 3))))
    (is (equal '(2 3) (call-autolisp-function cdr-fn '(1 2 3))))
    (is (equal '(1 2 3) (call-autolisp-function cons-fn 1 '(2 3))))
    (is (equal '(1 . 2) (call-autolisp-function cons-fn 1 2)))
    (is (equal '(1 2 3) (call-autolisp-function list-fn 1 2 3)))
    (is (null (call-autolisp-function list-fn)))))

(test builtin-append-length-nth-reverse
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((append-fn (autolisp-symbol-function (find-autolisp-symbol "APPEND")))
         (length-fn (autolisp-symbol-function (find-autolisp-symbol "LENGTH")))
         (nth-fn (autolisp-symbol-function (find-autolisp-symbol "NTH")))
         (reverse-fn (autolisp-symbol-function (find-autolisp-symbol "REVERSE"))))
    (is (null (call-autolisp-function append-fn)))
    (is (equal '(1 2 3 4) (call-autolisp-function append-fn '(1 2) '(3 4))))
    (is (equal '(1 2 . 3) (call-autolisp-function append-fn '(1 2) 3)))
    (is (= 3 (call-autolisp-function length-fn '(1 2 3))))
    (is (eql 30 (call-autolisp-function nth-fn 2 '(10 20 30 40))))
    (is (null (call-autolisp-function nth-fn 9 '(10 20 30 40))))
    (is (equal '(3 2 1) (call-autolisp-function reverse-fn '(1 2 3))))))

(test builtin-assoc
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((assoc-fn (autolisp-symbol-function (find-autolisp-symbol "ASSOC")))
         (foo (intern-autolisp-symbol "FOO"))
         (bar (intern-autolisp-symbol "BAR")))
    (is (equal '(1 . 2)
               (call-autolisp-function assoc-fn 1 '((0 . 1) (1 . 2) (2 . 3)))))
    (let* ((alist (list (cons bar 1) (cons foo 2)))
           (result (call-autolisp-function assoc-fn foo alist)))
      (is (eq result (second alist))
          "Symbol lookup is name-based and returns the matching alist entry."))
    (let* ((string-key-1 (clautolisp.autolisp-runtime:autolisp-read-from-string "\"foo\""))
           (string-key-2 (clautolisp.autolisp-runtime:autolisp-read-from-string "\"foo\""))
           (result (call-autolisp-function assoc-fn string-key-2
                                           (list (cons string-key-1 1)))))
      (is (consp result))
      (is (typep (car result) 'autolisp-string))
      (is (string= "foo" (autolisp-string-value (car result))))
      (is (= 1 (cdr result))))))

(test builtin-last-and-member
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((last-fn (autolisp-symbol-function (find-autolisp-symbol "LAST")))
         (member-fn (autolisp-symbol-function (find-autolisp-symbol "MEMBER")))
         (foo (intern-autolisp-symbol "FOO"))
         (bar (intern-autolisp-symbol "BAR")))
    (is (null (call-autolisp-function last-fn nil)))
    (is (eql 'e (call-autolisp-function last-fn '(a b c d e))))
    (is (equal '(d e) (call-autolisp-function last-fn '(a b c (d e)))))
    (is (equal '(c d e) (call-autolisp-function member-fn 'c '(a b c d e))))
    (is (null (call-autolisp-function member-fn 'q '(a b c d e))))
    (is (equal (list foo bar)
               (call-autolisp-function member-fn foo (list foo bar))))))

(test builtin-subst
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((subst-fn (autolisp-symbol-function (find-autolisp-symbol "SUBST")))
         (foo-1 (intern-autolisp-symbol "FOO"))
         (bar (intern-autolisp-symbol "BAR"))
         (string-old-1 (clautolisp.autolisp-runtime:autolisp-read-from-string "\"old\""))
         (string-old-2 (clautolisp.autolisp-runtime:autolisp-read-from-string "\"old\""))
         (string-new (clautolisp.autolisp-runtime:autolisp-read-from-string "\"new\"")))
    (is (equal '(a qq (c d) qq)
               (call-autolisp-function subst-fn 'qq 'b '(a b (c d) b))))
    (is (equal '(a b (qq rr) b)
               (call-autolisp-function subst-fn '(qq rr) '(c d) '(a b (c d) b))))
    (is (eq bar (call-autolisp-function subst-fn bar foo-1 foo-1)))
    (let ((result (call-autolisp-function subst-fn string-new string-old-2
                                          (list string-old-1 1))))
      (is (typep (first result) 'autolisp-string))
      (is (string= "new" (autolisp-string-value (first result)))))))

(test builtin-listp-and-vl-consp
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((listp-fn (autolisp-symbol-function (find-autolisp-symbol "LISTP")))
         (vl-consp-fn (autolisp-symbol-function (find-autolisp-symbol "VL-CONSP"))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function listp-fn '(a b c)))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function listp-fn nil))))
    (is (null (call-autolisp-function listp-fn 'a)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function vl-consp-fn '(a b c)))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function vl-consp-fn '(a . b)))))
    (is (null (call-autolisp-function vl-consp-fn nil)))
    (is (null (call-autolisp-function vl-consp-fn 'a)))))

(test builtin-vl-list*
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let ((fn (autolisp-symbol-function (find-autolisp-symbol "VL-LIST*"))))
    (is (eql 1 (call-autolisp-function fn 1)))
    (is (equal '(1 . 2) (call-autolisp-function fn 1 2)))
    (is (equal '(1 2 . 3) (call-autolisp-function fn 1 2 3)))
    (is (equal '(1 2 3 4) (call-autolisp-function fn 1 2 '(3 4))))
    (is (equal '((a) b c) (call-autolisp-function fn '(a) 'b '(c))))))

(test builtin-number-and-comparison-predicates
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((numberp-fn (autolisp-symbol-function (find-autolisp-symbol "NUMBERP")))
         (=-fn (autolisp-symbol-function (find-autolisp-symbol "=")))
         (/=-fn (autolisp-symbol-function (find-autolisp-symbol "/=")))
         (zerop-fn (autolisp-symbol-function (find-autolisp-symbol "ZEROP")))
         (minusp-fn (autolisp-symbol-function (find-autolisp-symbol "MINUSP")))
         (foo-string-1 (clautolisp.autolisp-runtime:autolisp-read-from-string "\"foo\""))
         (foo-string-2 (clautolisp.autolisp-runtime:autolisp-read-from-string "\"foo\""))
         (bar-string (clautolisp.autolisp-runtime:autolisp-read-from-string "\"bar\"")))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function numberp-fn 1))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function numberp-fn 1.0d0))))
    (is (null (call-autolisp-function numberp-fn foo-string-1)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function =-fn 1 1 1))))
    (is (null (call-autolisp-function =-fn 1 2)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function =-fn foo-string-1 foo-string-2))))
    (is (null (call-autolisp-function =-fn foo-string-1 bar-string)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function /=-fn 1 2 3))))
    (is (null (call-autolisp-function /=-fn 1 2 1)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function /=-fn foo-string-1 bar-string))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function zerop-fn 0))))
    (is (null (call-autolisp-function zerop-fn 7)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function minusp-fn -3))))
    (is (null (call-autolisp-function minusp-fn 0)))))

(test builtin-ordered-comparisons-and-numeric-conversions
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((<-fn (autolisp-symbol-function (find-autolisp-symbol "<")))
         (<=-fn (autolisp-symbol-function (find-autolisp-symbol "<=")))
         (>-fn (autolisp-symbol-function (find-autolisp-symbol ">")))
         (>=-fn (autolisp-symbol-function (find-autolisp-symbol ">=")))
         (abs-fn (autolisp-symbol-function (find-autolisp-symbol "ABS")))
         (fix-fn (autolisp-symbol-function (find-autolisp-symbol "FIX")))
         (float-fn (autolisp-symbol-function (find-autolisp-symbol "FLOAT"))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function <-fn 1 2 3))))
    (is (null (call-autolisp-function <-fn 1 3 2)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function <=-fn 1 1 2))))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function >-fn 3 2 1))))
    (is (null (call-autolisp-function >-fn 3 3 1)))
    (is (string= "T" (autolisp-symbol-name (call-autolisp-function >=-fn 3 3 1))))
    (is (= 7 (call-autolisp-function abs-fn -7)))
    (is (= 2.5d0 (call-autolisp-function abs-fn -2.5d0)))
    (is (= 12 (call-autolisp-function fix-fn 12.75d0)))
    (is (= -12 (call-autolisp-function fix-fn -12.75d0)))
    (is (typep (call-autolisp-function float-fn 7) 'double-float))
    (is (= 7.0d0 (call-autolisp-function float-fn 7)))
    (is (= 3.5d0 (call-autolisp-function float-fn 3.5d0)))))

(test builtin-string-primitives
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((strcat-fn (autolisp-symbol-function (find-autolisp-symbol "STRCAT")))
         (strlen-fn (autolisp-symbol-function (find-autolisp-symbol "STRLEN")))
         (substr-fn (autolisp-symbol-function (find-autolisp-symbol "SUBSTR")))
         (ascii-fn (autolisp-symbol-function (find-autolisp-symbol "ASCII")))
         (chr-fn (autolisp-symbol-function (find-autolisp-symbol "CHR")))
         (hello (clautolisp.autolisp-runtime:make-autolisp-string "Hello"))
         (space (clautolisp.autolisp-runtime:make-autolisp-string " "))
         (world (clautolisp.autolisp-runtime:make-autolisp-string "World"))
         (empty (clautolisp.autolisp-runtime:make-autolisp-string "")))
    (is (string= "" (autolisp-string-value (call-autolisp-function strcat-fn))))
    (is (string= "Hello World"
                 (autolisp-string-value
                  (call-autolisp-function strcat-fn hello space world))))
    (is (= 0 (call-autolisp-function strlen-fn)))
    (is (= 0 (call-autolisp-function strlen-fn empty)))
    (is (= 10 (call-autolisp-function strlen-fn hello world)))
    (is (string= "Hello"
                 (autolisp-string-value
                  (call-autolisp-function substr-fn hello 1))))
    (is (string= "ell"
                 (autolisp-string-value
                  (call-autolisp-function substr-fn hello 2 3))))
    (is (string= ""
                 (autolisp-string-value
                  (call-autolisp-function substr-fn hello 10))))
    (is (= 72 (call-autolisp-function ascii-fn hello)))
    (is (string= "A"
                 (autolisp-string-value
                  (call-autolisp-function chr-fn 65))))))

(test builtin-file-primitives
  (reset-autolisp-symbol-table)
  (install-core-builtins)
  (let* ((open-fn (autolisp-symbol-function (find-autolisp-symbol "OPEN")))
         (close-fn (autolisp-symbol-function (find-autolisp-symbol "CLOSE")))
         (read-line-fn (autolisp-symbol-function (find-autolisp-symbol "READ-LINE")))
         (read-char-fn (autolisp-symbol-function (find-autolisp-symbol "READ-CHAR")))
         (write-line-fn (autolisp-symbol-function (find-autolisp-symbol "WRITE-LINE")))
         (write-char-fn (autolisp-symbol-function (find-autolisp-symbol "WRITE-CHAR")))
         (findfile-fn (autolisp-symbol-function (find-autolisp-symbol "FINDFILE")))
         (findtrustedfile-fn (autolisp-symbol-function (find-autolisp-symbol "FINDTRUSTEDFILE")))
         (directory (format nil "/tmp/clautolisp-builtins-core-~D/" (random 1000000000)))
         (relative-name "sample.txt")
         (trusted-name "trusted.txt")
         (path (concatenate 'string directory relative-name))
         (trusted-path (concatenate 'string directory trusted-name))
         (resolved-path nil)
         (resolved-trusted-path nil)
         (path-string (clautolisp.autolisp-runtime:make-autolisp-string relative-name))
         (write-mode (clautolisp.autolisp-runtime:make-autolisp-string "w"))
         (read-mode (clautolisp.autolisp-runtime:make-autolisp-string "r")))
    (ensure-directories-exist directory)
    (set-autolisp-current-directory directory)
    (set-autolisp-support-paths (list directory))
    (set-autolisp-trusted-paths (list directory))
    (let ((file (call-autolisp-function open-fn path-string write-mode)))
      (is (typep file 'autolisp-file))
      (is (typep (call-autolisp-function write-line-fn
                                         (clautolisp.autolisp-runtime:make-autolisp-string "alpha")
                                         file)
                 'autolisp-string))
      (is (= 66 (call-autolisp-function write-char-fn 66 file)))
      (is (null (call-autolisp-function close-fn file))))
    (let ((file (call-autolisp-function open-fn path-string read-mode)))
      (is (typep file 'autolisp-file))
      (is (string= "alpha"
                   (autolisp-string-value
                    (call-autolisp-function read-line-fn file))))
      (is (= 66 (call-autolisp-function read-char-fn file)))
      (is (null (call-autolisp-function read-line-fn file)))
      (is (null (call-autolisp-function close-fn file))))
    (with-open-file (stream trusted-path
                            :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
      (write-line "trusted" stream))
    (setf resolved-path (namestring (probe-file path))
          resolved-trusted-path (namestring (probe-file trusted-path)))
    (is (string= resolved-path
                 (autolisp-string-value
                  (call-autolisp-function findfile-fn
                                          (clautolisp.autolisp-runtime:make-autolisp-string relative-name)))))
    (is (string= resolved-trusted-path
                 (autolisp-string-value
                  (call-autolisp-function findtrustedfile-fn
                                          (clautolisp.autolisp-runtime:make-autolisp-string trusted-name)))))
    (is (null (call-autolisp-function findfile-fn
                                      (clautolisp.autolisp-runtime:make-autolisp-string "missing.txt"))))
    (ignore-errors (delete-file path))
    (ignore-errors (delete-file trusted-path))
    (ignore-errors (delete-file directory))))
