#!/usr/bin/env python3
"""Generate cador/source/sysvar-scopes.lisp: the names of the system variables
SAVED IN THE DRAWING (inventory :saved-in :drawing). Every other variable --
:registry, :preference, :session -- belongs to the application, so all open
documents share it (cador-multidocument-host; clautolisp-cador-spec D2 §I.6).

    generate-sysvar-scopes.py INVENTORY.sexp OUTPUT.lisp
"""
import re
import sys

def main(argv):
    text = open(argv[1], encoding='utf-8').read()
    names = []
    tiers = []
    # D1 §4 / C4: three tiers. The inventory's :preference lives in the
    # registry profile; :session is not saved at all.
    tier_of = {':drawing': ':drawing', ':registry': ':registry',
               ':preference': ':registry', ':session': ':not-saved'}
    for m in re.finditer(r':name "([^"]+)"(.*?)(?=\(\s*:name "|\Z)', text, re.S):
        saved = re.search(r':saved-in (\S+)', m.group(2))
        if saved and saved.group(1) == ':drawing':
            names.append(m.group(1))
        if saved and saved.group(1) in tier_of:
            tiers.append((m.group(1), tier_of[saved.group(1)]))
    lines = [
        ';;;; -*- Mode: Lisp; coding: utf-8 -*-',
        ';;;; GENERATED by clautolisp/tools/generate-sysvar-scopes.py -- DO NOT EDIT.',
        ';;;; The system variables the inventory says are SAVED IN THE DRAWING; every',
        ';;;; other one is the application\'s, shared by all open documents. Regenerate:',
        ';;;;   python3 tools/generate-sysvar-scopes.py \\',
        ';;;;     ../autolisp-spec/documentation/system-variables-inventory.sexp \\',
        ';;;;     cador/source/sysvar-scopes.lisp',
        '',
        '(in-package #:clautolisp.cador)',
        '',
        '(defparameter *drawing-saved-sysvars*',
        '  (let ((table (make-hash-table :test #\'equalp)))',
        '    (dolist (name \'(',
    ]
    for i in range(0, len(names), 4):
        lines.append('                    ' + ' '.join('"%s"' % n for n in names[i:i + 4]))
    lines += [
        '                    ))',
        '      (setf (gethash name table) t))',
        '    table)',
        '  "Name -> T for each system variable saved in the drawing (%d)."' % len(names) + ')',
        '',
        '(defun drawing-saved-sysvar-p (name)',
        '  "True when system variable NAME is saved in the drawing (one per document),',
        'false when it is the application\'s (registry / preference / session: shared)."',
        '  (values (gethash name *drawing-saved-sysvars*)))',
        '',
        '(defparameter *sysvar-scope-tiers*',
        '  (let ((table (make-hash-table :test #\'equalp)))',
        '    (loop for (name tier) on \'(',
    ]
    for i in range(0, len(tiers), 3):
        lines.append('                    ' + ' '.join('"%s" %s' % t for t in tiers[i:i + 3]))
    lines += [
        '                    ) by #\'cddr',
        '          do (setf (gethash name table) tier))',
        '    table)',
        '  "Name -> scope tier (:DRAWING / :REGISTRY / :NOT-SAVED) of each inventoried',
        'system variable (%d): inventory :saved-in, :preference counted as :registry,' % len(tiers),
        ':session as :not-saved (D1 §4, C4).")',
        '',
        '(defun sysvar-scope-tier (name)',
        '  "The scope tier of system variable NAME, or NIL when it is not inventoried."',
        '  (values (gethash name *sysvar-scope-tiers*)))',
        '',
    ]
    open(argv[2], 'w', encoding='utf-8').write('\n'.join(lines))
    print(len(names), 'drawing-saved sysvars')

if __name__ == '__main__':
    main(sys.argv)
