#!/usr/bin/env python3
"""Generate autolisp-runtime/source/text-metrics.lisp from measured TEXTBOX.

clautolisp's TEXTBOX and its TEXT bounding box used one 0.6 width ratio
for every character. The vendors measure the real font. probes/sources/
probe-block-walk.lsp asks them, at height 1 in the Standard style: TEXTBOX
of every printable ASCII character alone, and repeated ten times.

  alone    -> left bearing, ink right edge, ink bottom and top
  ten      -> 9 advances + the last glyph's ink, so  advance = (x1_10 - x1_1) / 9

AutoCAD 2022 and BricsCAD (macOS) agree on every horizontal value and on
every glyph that touches the baseline; there is no kerning (six pairs measure
exactly the sum of their advances). They differ only in how a box that does
not straddle the baseline is REPORTED, and on spaces -- rules applied in
TEXT-INK-BOX, not data. So the table is BricsCAD's true glyph extents.

    generate-text-metrics.py BRICSCAD-RESULTS.sexp AUTOCAD-RESULTS.sexp OUTPUT
"""
import re
import sys

num = r'(-?[0-9.eE+-]+)'
box = r'\(VALUE \(' + num + ' ' + num + ' ' + num + r'\) \(' + num + ' ' + num + ' ' + num + r'\)\)'
row = re.compile(r'\(SUITE \. "text-metrics"\) \(CASE \. "textbox (10|1) x char (\d+)"\) '
                 r'\(STATUS \. "ok"\) ' + box)


def load(path):
    out = {}
    for m in row.finditer(open(path, encoding='utf-8', errors='replace').read()):
        out[(int(m.group(1)), int(m.group(2)))] = (
            float(m.group(3)), float(m.group(4)), float(m.group(6)), float(m.group(7)))
    return out


def table(x):
    t = {}
    for code in range(32, 127):
        one, ten = x[(1, code)], x[(10, code)]
        lsb, y0, ink_r, y1 = one
        t[code] = (lsb, ink_r, (ten[2] - one[2]) / 9.0, y0, y1)
    return t


def main(argv):
    brx, acad, out = argv[1], argv[2], argv[3]
    tb, ta = table(load(brx)), table(load(acad))
    # The premise of one table: the horizontal values agree.
    for code in range(33, 127):
        for i in (0, 1, 2):
            if abs(tb[code][i] - ta[code][i]) > 1e-4:
                raise SystemExit("horizontal metric of %r differs: %r vs %r"
                                 % (chr(code), tb[code], ta[code]))
    lines = [
        ";;;; -*- mode:lisp; coding:utf-8 -*-",
        ";;;;",
        ";;;; GENERATED by clautolisp/tools/generate-text-metrics.py -- DO NOT EDIT.",
        ";;;;",
        ";;;; The Standard text style's glyph metrics, MEASURED with TEXTBOX at",
        ";;;; height 1 (probes/sources/probe-block-walk.lsp) on BricsCAD macOS",
        ";;;; (%s)" % brx.split('probe-results/')[-1],
        ";;;; and checked against AutoCAD 2022",
        ";;;; (%s)." % acad.split('probe-results/')[-1],
        ";;;; Regenerate: make -C clautolisp text-metrics",
        "",
        "(in-package #:clautolisp.autolisp-runtime)",
        "",
        "(defparameter *standard-glyph-metrics*",
        "  (let ((table (make-array 127 :initial-element nil)))",
        "    (loop for (code . metrics) in",
        "          '(",
    ]
    for code in range(32, 127):
        lsb, ink_r, adv, y0, y1 = tb[code]
        lines.append("            (%d %r %r %r %r %r)  ; %s"
                     % (code, round(lsb, 9), round(ink_r, 9), round(adv, 9),
                        round(y0, 9), round(y1, 9), repr(chr(code))))
    lines += [
        "            )",
        "          do (setf (aref table code) (map 'vector (lambda (x) (coerce x 'double-float)) metrics)))",
        "    table)",
        '  "Per ASCII code: #(LEFT-BEARING INK-RIGHT ADVANCE INK-BOTTOM INK-TOP) at',
        'height 1. Generated; see the file header.")',
        "",
    ]
    with open(out, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    print("wrote", out, len(tb), "glyphs")


if __name__ == "__main__":
    main(sys.argv)
