#!/usr/bin/env python3
"""Generate cador/source/template-defaults.lisp: the imperial-template
(AutoCAD acad.dwt) and metric-template (acadiso.dwt) values of the sysvars
whose inventory :default is (:drawing).

The catalogue (sysvar-catalogue.lisp) installs a kind-appropriate zero on
every (:drawing) cell -- DIMASZ 0.0, DIMSTYLE "", CMLSCALE 0.0, GRIDUNIT
(0 0) -- so a fresh headless drawing looked like no drawing any vendor
makes. The inventory keeps the documented values in :divergence, e.g.
"default AutoCAD 0.1800 (imperial) or 2.5000 (metric)" (the AutoCAD 2026
"Initial value"), or "default BricsCAD 1 (imperial) or 25 (metric)" for a
BricsCAD-only cell (its "Default value"). This takes both; a cell whose
text states none is reported and left on the stand-in.

    generate-template-defaults.py INVENTORY.sexp OUTPUT.lisp
"""
import re
import sys

def entries(text):
    for m in re.finditer(r':name "([^"]+)"(.*?)(?=\(\s*:name "|\Z)', text, re.S):
        yield m.group(1), m.group(2)

def field(body, key):
    m = re.search(r':' + key + r' ("(?:[^"\\]|\\.)*"|\S+)', body)
    return m.group(1) if m else None

def lisp_value(kind, raw):
    raw = raw.strip().strip('"')
    if kind == ':real':
        nums = re.findall(r'-?\d+(?:\.\d+)?', raw)
        return ('%sd0' % nums[0]) if len(nums) == 1 else None
    if kind in (':short', ':integer', ':long'):
        return raw if re.fullmatch(r'-?\d+', raw) else None
    if kind == ':string':
        return '"%s"' % raw
    if kind in (':2d-point', ':point', ':3d-point'):
        nums = re.findall(r'-?\d+(?:\.\d+)?', raw)
        return '(%s)' % ' '.join(n + 'd0' for n in nums) if len(nums) in (2, 3) else None
    return None

def template_values(kind, divergence):
    """(IMPERIAL METRIC) Lisp texts, either None when not stated."""
    m = re.search(r'default (?:AutoCAD|BricsCAD) (.+?) \(imperial\)(?: or (.+?) \(metric\))?',
                  divergence)
    if not m:
        return None, None
    return (lisp_value(kind, m.group(1)),
            lisp_value(kind, m.group(2)) if m.group(2) else None)

def table(name, rows, doc):
    return ['(defparameter %s' % name, "  '("] + rows + ['    )', '  "%s")' % doc, '']

def main(argv):
    text = open(argv[1], encoding='utf-8').read()
    imperial, metric, missing = [], [], []
    for name, body in entries(text):
        if field(body, 'default') != '(:drawing)':
            continue
        div = (field(body, 'divergence') or '""')[1:-1].replace('\\"', '"')
        imp, met = template_values(field(body, 'type'), div)
        if imp is None:
            missing.append(name)
        else:
            imperial.append('    ("%s" . %s)' % (name, imp))
        if met is not None:
            metric.append('    ("%s" . %s)' % (name, met))
    out = [
        ';;;; -*- Mode: Lisp; coding: utf-8 -*-',
        ';;;; GENERATED by clautolisp/tools/generate-template-defaults.py -- DO NOT EDIT.',
        ';;;; Imperial-template (acad.dwt) and metric-template (acadiso.dwt) values of',
        ";;;; the (:drawing) sysvars, from the inventory's documented",
        ';;;; "default AutoCAD|BricsCAD X (imperial) or Y (metric)". Regenerate:',
        ';;;;   python3 tools/generate-template-defaults.py \\',
        ';;;;     ../autolisp-spec/documentation/system-variables-inventory.sexp \\',
        ';;;;     cador/source/template-defaults.lisp',
        ';;;; Left on the catalogue stand-in (no template value stated): %s' % (' '.join(missing) or 'none'),
        '',
        '(in-package #:clautolisp.cador)',
        '',
    ] + table('*imperial-template-defaults*', imperial,
              '(NAME . VALUE): what a fresh imperial AutoCAD drawing holds in the\n'
              'drawing-dependent sysvars the catalogue can only stand in for.') \
      + table('*metric-template-defaults*', metric,
              '(NAME . VALUE): what a fresh metric drawing holds instead, where the\n'
              'documentation states a metric value.')
    open(argv[2], 'w', encoding='utf-8').write('\n'.join(out))
    print(len(imperial), 'imperial,', len(metric), 'metric;', len(missing), 'left:', ' '.join(missing))

if __name__ == '__main__':
    main(sys.argv)
