#!/usr/bin/env python3
"""Generate autolisp-runtime/source/operator-availability.lisp from the spec.

deferred-clautolisp-out-of-dialect-warnings: clautolisp warns, once per
operator and session, when a VENDOR-ONLY operator is called under a dialect
that does not own it (autolisp-spec ch.25, case 1: an extension warns in every
dialect except its owner's and lax). WHICH operators are vendor-only is the
spec's call, not clautolisp's: each Function Entry has an `*** Availability'
section, and autolisp-spec's build-paged-spec.el turns it into the A / B / AB
flag of build/pages/symbols.txt (SYMBOL<TAB>KIND<TAB>BASENAME<TAB>FLAGS).

This keeps the rows whose flag is exactly `A' (AutoCAD-only) or `B'
(BricsCAD-only), for kinds Function and Special Form, and writes them as a
committed Lisp table -- the same pattern as cador's spec-derived
bricscad-sysvar-overrides.lisp, so clautolisp builds without the spec tree.

Left out on purpose:
  - AB and unflagged rows: portable, or not vendor data;
  - CLAL-* / CLAUTOLISP-* names: clautolisp's OWN extensions, which have their
    own out-of-dialect notices; an Availability section that mentions a
    vendor's analogue (CLAL-FILE-ENCODING cites vle-file-encoding) must not
    make them vendor-owned.

    generate-operator-availability.py SYMBOLS.TXT [OUTPUT]
    generate-operator-availability.py --check SYMBOLS.TXT OUTPUT
"""
import sys

OWNERS = {"A": ":autocad", "B": ":bricscad"}
KINDS = {"Function", "Special Form"}
OWN_PREFIXES = ("CLAL-", "CLAUTOLISP-")


def rows(symbols_path):
    out = {}
    with open(symbols_path, encoding="utf-8") as f:
        for line in f:
            fields = line.rstrip("\n").split("\t")
            if len(fields) != 4:
                continue
            name, kind, _basename, flags = fields
            if kind not in KINDS or flags not in OWNERS:
                continue
            if name.startswith(OWN_PREFIXES):
                continue
            out[name] = OWNERS[flags]
    return sorted(out.items())


def render(entries):
    autocad = sum(1 for _, o in entries if o == ":autocad")
    bricscad = len(entries) - autocad
    lines = [
        ";;;; -*- mode:lisp; coding:utf-8 -*-",
        ";;;;",
        ";;;; GENERATED by clautolisp/tools/generate-operator-availability.py -- DO NOT EDIT.",
        ";;;;",
        ";;;; The VENDOR-ONLY AutoLISP operators, from the `*** Availability' section",
        ";;;; of each autolisp-spec Function Entry (build/pages/symbols.txt, flag A or B).",
        ";;;; A wrong row is fixed in the SPEC, then regenerated:",
        ";;;;     make -C clautolisp operator-availability",
        ";;;; and `make -C clautolisp check-operator-availability' fails on drift.",
        ";;;;",
        ";;;; %d AutoCAD-only, %d BricsCAD-only." % (autocad, bricscad),
        "",
        "(in-package #:clautolisp.autolisp-runtime)",
        "",
        "(defparameter *vendor-only-operators*",
        "  '(",
    ]
    for name, owner in entries:
        lines.append('    ("%s" . %s)' % (name, owner))
    lines.append("    )")
    lines.append('  "Alist (OPERATOR-NAME . OWNER), OWNER :AUTOCAD or :BRICSCAD: the')
    lines.append("operators only that vendor provides, per the spec. Generated; see the")
    lines.append('file header.")')
    lines.append("")
    return "\n".join(lines)


def main(argv):
    check = len(argv) > 1 and argv[1] == "--check"
    args = argv[2:] if check else argv[1:]
    if not args:
        print(__doc__, file=sys.stderr)
        return 2
    text = render(rows(args[0]))
    if check:
        with open(args[1], encoding="utf-8") as f:
            if f.read() != text:
                print("check-operator-availability: %s is stale; run "
                      "make -C clautolisp operator-availability" % args[1],
                      file=sys.stderr)
                return 1
        print("check-operator-availability: OK")
        return 0
    if len(args) > 1:
        with open(args[1], "w", encoding="utf-8") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
