(defpackage #:clautolisp.autolisp-file-compat
  (:use #:cl)
  (:export
   #:file-compat-scenario
   #:make-file-compat-scenario
   #:file-compat-scenario-name
   #:file-compat-scenario-description
   #:file-compat-scenario-kind
   #:file-compat-scenario-root
   #:file-compat-scenario-relative-path
   #:file-compat-scenario-classification
   #:file-compat-scenario-tags
   #:file-compat-scenario-external-format
   #:file-compat-scenario-newline-mode
   #:file-compat-scenario-setup-files
   #:file-compat-scenario-current-directory
   #:file-compat-scenario-support-paths
   #:file-compat-scenario-trusted-paths
   #:file-compat-scenario-builtin-name
   #:file-compat-scenario-arguments
   #:file-compat-scenario-steps
   #:file-compat-scenario-result-ref
   #:file-compat-scenario-expected-value
   #:file-compat-scenario-artifact-relative-path
   #:file-compat-scenario-expected-artifact-exists-p
   #:file-compat-scenario-input-text
   #:file-compat-scenario-input-bytes
   #:file-compat-scenario-expected-text
   #:file-compat-scenario-expected-lines
   #:file-compat-scenario-expected-bytes
   #:file-compat-artifact
   #:make-file-compat-artifact
   #:file-compat-artifact-path
   #:file-compat-artifact-bytes
   #:file-compat-artifact-text
   #:file-compat-artifact-lines
   #:file-compat-check
   #:make-file-compat-check
   #:file-compat-check-name
   #:file-compat-check-passed-p
   #:file-compat-check-message
   #:file-compat-report
   #:make-file-compat-report
   #:file-compat-report-scenario
   #:file-compat-report-runner
   #:file-compat-report-checks
   #:file-compat-report-artifact
   #:file-compat-summary
   #:make-file-compat-summary
   #:file-compat-summary-total-scenarios
   #:file-compat-summary-passed-scenarios
   #:file-compat-summary-failed-scenarios
   #:file-compat-summary-total-checks
   #:file-compat-summary-passed-checks
   #:file-compat-summary-failed-checks
   #:load-scenario-file
   #:scenario->plist
   #:report->plist
   #:summary->plist
   #:scenario-value->runtime-value
   #:normalize-newlines
   #:read-file-bytes
   #:write-file-bytes
   #:read-file-text
   #:write-file-text
   #:capture-file-artifact
   #:compare-bytes
   #:compare-text
   #:compare-lines
   #:report-passed-p
   #:summarize-reports
   #:scenario-matches-tags-p
   #:collect-scenario-file-paths
   #:emit-json-value
   #:emit-report
   #:run-local-roundtrip-scenario
   #:run-builtin-scenario
   #:run-scenario))
