(defpackage #:clautolisp.autolisp-file-compat
  (:use #:cl)
  (:export
   #:file-compat-scenario
   #:make-file-compat-scenario
   #:file-compat-scenario-name
   #:file-compat-scenario-description
   #:file-compat-scenario-root
   #:file-compat-scenario-relative-path
   #:file-compat-scenario-external-format
   #:file-compat-scenario-newline-mode
   #:file-compat-scenario-input-text
   #:file-compat-scenario-input-bytes
   #:file-compat-scenario-expected-text
   #:file-compat-scenario-expected-bytes
   #:file-compat-artifact
   #:make-file-compat-artifact
   #:file-compat-artifact-path
   #:file-compat-artifact-bytes
   #:file-compat-artifact-text
   #:file-compat-artifact-lines
   #:file-compat-check
   #:make-file-compat-check
   #:file-compat-check-name
   #:file-compat-check-passed-p
   #:file-compat-check-message
   #:file-compat-report
   #:make-file-compat-report
   #:file-compat-report-scenario
   #:file-compat-report-runner
   #:file-compat-report-checks
   #:file-compat-report-artifact
   #:load-scenario-file
   #:scenario->plist
   #:report->plist
   #:normalize-newlines
   #:read-file-bytes
   #:write-file-bytes
   #:read-file-text
   #:write-file-text
   #:capture-file-artifact
   #:compare-bytes
   #:compare-text
   #:compare-lines
   #:emit-report
   #:run-local-roundtrip-scenario
   #:run-scenario))
