(defpackage #:clautolisp.autolisp-reader.tests
  (:use #:cl)
  (:import-from #:fiveam
                #:def-suite
                #:in-suite
                #:test
                #:is
                #:run
                #:explain!
                #:results-status)
  (:import-from #:clautolisp.autolisp-reader
                #:comment-object
                #:comment-object-kind
                #:comment-object-text
                #:concrete-list-object
                #:concrete-list-object-items
                #:cons-object
                #:cons-object-dotted-p
                #:cons-object-elements
                #:cons-object-tail
                #:diagnostic
                #:diagnostic-code
                #:diagnostic-severity
                #:diagnostic-span
                #:source-span-source-name
                #:dot-object
                #:integer-object
                #:integer-object-value
                #:quote-object
                #:quote-object-object
                #:read-forms-from-file
                #:read-concrete-from-string
                #:read-forms-from-string
                #:read-result-diagnostics
                #:read-result-objects
                #:real-object
                #:real-object-overflowed-integer-p
                #:string-object
                #:string-object-value
                #:symbol-object
                #:symbol-object-canonical-name
                #:token
                #:token-kind
                #:token-lexeme
                #:tokenize-string
                #:autolisp-dialect
                #:autolisp-dialect-name
                #:autolisp-dialect-token-mode
                #:autolisp-dialect-extended-string-escapes-p
                #:autolisp-dialect-warn-on-integer-overflow-p
                #:autolisp-dialect-canonical-case
                #:autolisp-dialect-hex-float-atof-p
                #:autolisp-dialect-open-ccs-mode-p
                #:autolisp-dialect-strict
                #:autolisp-dialect-autocad-2026
                #:autolisp-dialect-bricscad-v26
                #:find-autolisp-dialect
                #:reader-options-from-dialect
                #:reader-options-token-mode
                #:reader-options-extended-string-escapes-p
                #:reader-options-warn-on-integer-overflow-p
                #:reader-options-canonical-case)
  (:export #:run-all-tests
           #:autolisp-reader-suite))
