;;;; -*- Mode: Lisp; coding: utf-8 -*-
;;;; GENERATED by clautolisp/tools/generate-sysvar-scopes.py -- DO NOT EDIT.
;;;; The system variables the inventory says are SAVED IN THE DRAWING; every
;;;; other one is the application's, shared by all open documents. Regenerate:
;;;;   python3 tools/generate-sysvar-scopes.py \
;;;;     ../autolisp-spec/documentation/system-variables-inventory.sexp \
;;;;     cador/source/sysvar-scopes.lisp

(in-package #:clautolisp.cador)

(defparameter *drawing-saved-sysvars*
  (let ((table (make-hash-table :test #'equalp)))
    (dolist (name '(
                    "3DDWFPREC" "AMPOWERDIMDISPLAY" "AMSYMSCALE" "ANGBASE"
                    "ANGDIR" "ANNOALLVISIBLE" "ANNOMONITOR" "ANNOTATIVEDWG"
                    "ATTMODE" "AUNITS" "AUPREC" "BACKZ"
                    "BIMMATCHPROP" "BLOCKLEVELOFDETAIL" "BOLTINGASMDEFAULTLENGTHINCREMENT" "BOLTINGASMDEFAULTNUT"
                    "BOLTINGASMDEFAULTNUTSNUMBER" "BOLTINGASMDEFAULTSTUD" "CAMERADISPLAY" "CAMERAHEIGHT"
                    "CANNOSCALE" "CANNOSCALEVALUE" "CECOLOR" "CELTSCALE"
                    "CELTYPE" "CELWEIGHT" "CENTERCROSSGAP" "CENTERCROSSSIZE"
                    "CENTEREXE" "CENTERLAYER" "CENTERLTSCALE" "CENTERLTYPE"
                    "CENTERLTYPEFILE" "CENTERMARKEXE" "CETRANSPARENCY" "CGEOCS"
                    "CHAMFERA" "CHAMFERB" "CHAMFERC" "CHAMFERD"
                    "CIRCULARARROWHEADLENGTH" "CIRCULARARROWHEADWIDTH" "CIRCULARARROWLEADERRADIUS" "CIRCULARARROWLEADERROTATION"
                    "CIRCULARARROWTHICKNESS" "CLAYER" "CLAYOUT" "CMATERIAL"
                    "CMLEADERSTYLE" "CMLJUST" "CMLSCALE" "CMLSTYLE"
                    "COMPAREFRONT" "COMPAREHATCH" "COMPARERCMARGIN" "COMPARERCSHAPE"
                    "COMPARESHOW1" "COMPARESHOW2" "COMPARESHOWCOMMON" "COMPARESHOWCONTEXT"
                    "COMPARESHOWRC" "COMPARETEXT" "COMPARETOLERANCE" "CPLOTSTYLE"
                    "CTAB" "CTABLESTYLE" "CVALLOWBREAKLINECROSSINGS" "CVANGLESAMPLINGINTERVAL"
                    "CVARCTESSELLATIONGRADING" "CVARCTESSELLATIONSURFACE" "CVARCTESSELLATIONTEMPLATEELEMENT" "CVASSOCIATIVITY"
                    "CVDEFAULTCURVETYPEHA" "CVDEFAULTCURVETYPEVA" "CVELEVATIONATBREAKLINECROSSINGS" "CVGRADEUNIT"
                    "CVGRADEUNITPREC" "CVIEWDETAILSTYLE" "CVLENGTHSAMPLINGINTERVAL" "CVPORT"
                    "CVSLOPEUNIT" "CVSLOPEUNITPREC" "CVSTATIONUNIT" "CVSTATIONUNITPREC"
                    "DBCSTATE" "DEFAULTLIGHTING" "DEFAULTLIGHTINGTYPE" "DEFAULTSPACEHEIGHT"
                    "DGNFRAME" "DIMADEC" "DIMALT" "DIMALTD"
                    "DIMALTF" "DIMALTRND" "DIMALTTD" "DIMALTTZ"
                    "DIMALTU" "DIMALTZ" "DIMANNO" "DIMAPOST"
                    "DIMARCSYM" "DIMASO" "DIMASSOC" "DIMASZ"
                    "DIMATFIT" "DIMAUNIT" "DIMAZIN" "DIMBLK"
                    "DIMBLK1" "DIMBLK2" "DIMCEN" "DIMCLRD"
                    "DIMCLRE" "DIMCLRT" "DIMDEC" "DIMDLE"
                    "DIMDLI" "DIMDSEP" "DIMEXE" "DIMEXO"
                    "DIMFIT" "DIMFRAC" "DIMFXL" "DIMFXLON"
                    "DIMGAP" "DIMJOGANG" "DIMJUST" "DIMLAYER"
                    "DIMLDRBLK" "DIMLFAC" "DIMLIM" "DIMLTEX1"
                    "DIMLTEX2" "DIMLTYPE" "DIMLUNIT" "DIMLWD"
                    "DIMLWE" "DIMMARKTYPE" "DIMPOST" "DIMRND"
                    "DIMSAH" "DIMSCALE" "DIMSD1" "DIMSD2"
                    "DIMSE1" "DIMSE2" "DIMSHO" "DIMSOXD"
                    "DIMSTYLE" "DIMTAD" "DIMTDEC" "DIMTFAC"
                    "DIMTFILL" "DIMTFILLCLR" "DIMTIH" "DIMTIX"
                    "DIMTM" "DIMTMOVE" "DIMTOFL" "DIMTOH"
                    "DIMTOL" "DIMTOLJ" "DIMTP" "DIMTSZ"
                    "DIMTVP" "DIMTXSTY" "DIMTXT" "DIMTXTDIRECTION"
                    "DIMTZIN" "DIMUNIT" "DIMUPT" "DIMZIN"
                    "DISPLAYAXES" "DISPLAYSIDESANDENDS" "DISPSILH" "DMRECOGNIZE"
                    "DRAGVS" "DRAWINGVIEWENTS" "DRAWINGVIEWQUALITY" "DRAWORDERCTL"
                    "DWFFRAME" "DWGGUIDCLOUDAI" "DXEVAL" "ELEVATION"
                    "EXPORTMODELSPACE" "EXPORTPAGESETUP" "EXPORTPAPERSPACE" "EXPVALUE"
                    "EXPWHITEBALANCE" "EXTMAX" "EXTMIN" "EXTNAMES"
                    "FACETRES" "FIELDEVAL" "FILLETRAD" "FILLETWELDINGCOMBINEADJACENT"
                    "FILLETWELDINGMAXGAPRATIO" "FILLETWELDINGZSIZE" "FILLMODE" "FITTINGRADIUSTYPE"
                    "FITTINGRADIUSVALUE" "FLANGEASMDEFAULTGASKET" "FRAME" "FRONTZ"
                    "GEOMAPMODE" "GEOMARKERVISIBILITY" "GEOMARKPOSITIONSIZE" "GRIDDISPLAY"
                    "GRIDMAJOR" "GRIDMODE" "GRIDUNIT" "HALOGAP"
                    "HANDLES" "HIDETEXT" "HPBACKGROUNDCOLOR" "HPCOLOR"
                    "HPLAYER" "HPORIGIN" "HPTRANSPARENCY" "HYPERLINKBASE"
                    "IBLENVIRONMENT" "IMAGEFRAME" "INDEXCTL" "INSBASE"
                    "INSUNITS" "INTERFERECOLOR" "INTERFEREOBJVS" "INTERFEREVPVS"
                    "INTERIORELEVATIONMINLENGTH" "INTERIORELEVATIONOFFSET" "INTERSECTIONCOLOR" "INTERSECTIONDISPLAY"
                    "ISOLINES" "LATITUDE" "LAYEREVAL" "LAYERNOTIFY"
                    "LENSLENGTH" "LEVELOFDETAIL" "LIGHTGLYPHDISPLAY" "LIGHTINGUNITS"
                    "LIGHTSINBLOCKS" "LIMCHECK" "LIMMAX" "LIMMIN"
                    "LINEARARROWHEADLENGTH" "LINEARARROWHEADWIDTH" "LINEARARROWTHICKNESS" "LINEARBRIGHTNESS"
                    "LINEARCONTRAST" "LOFTANG1" "LOFTANG2" "LOFTMAG1"
                    "LOFTMAG2" "LOFTNORMALS" "LOFTPARAM" "LOGFILENAME"
                    "LONGITUDE" "LTSCALE" "LUNITS" "LUPREC"
                    "LWDISPLAY" "MAXACTVP" "MEASUREMENT" "MESHTYPE"
                    "MIRRHATCH" "MIRRTEXT" "MLEADERLAYER" "MLEADERSCALE"
                    "MSLTSCALE" "MSOLESCALE" "NAVVCUBEDISPLAY" "NORTHDIRECTION"
                    "OBSCUREDCOLOR" "OBSCUREDLTYPE" "OLEFRAME" "OLESTARTUP"
                    "ORTHOMODE" "PDFFRAME" "PDMODE" "PDSIZE"
                    "PELLIPSE" "PERSPECTIVE" "PLINEGEN" "PLINEWID"
                    "POINTCLOUDCLIPFRAME" "POINTCLOUDLIGHTING" "POINTCLOUDLIGHTSOURCE" "POINTCLOUDLOD"
                    "POINTCLOUDPOINTSIZE" "POINTCLOUDSHADING" "POINTCLOUDVISRETAIN" "PREVIEWTYPE"
                    "PROJECTIONTYPE" "PROJECTLOCATIONVISIBILITY" "PROJECTNAME" "PROXYGRAPHICS"
                    "PSLTSCALE" "PSOLHEIGHT" "PSOLWIDTH" "PSTYLEMODE"
                    "PSVPSCALE" "PUCSBASE" "QTEXTMODE" "REALWORLDSCALE"
                    "REDUCELENGTHTYPE" "REDUCELENGTHVALUE" "REGENMODE" "RENDERCOMPOSITIONMATERIAL"
                    "RENDERLEVEL" "RENDERLIGHTCALC" "RENDERTARGET" "RENDERTIME"
                    "REVCLOUDLAYER" "RVTRFALEVELOFDETAIL" "SECTIONOFFSETINC" "SECTIONRESULTINTERVAL"
                    "SECTIONTHICKNESSINC" "SHADEDGE" "SHADEDIF" "SHOWHIST"
                    "SHOWIDSPROPERTIESONLY" "SITELOCATIONVISIBILITY" "SKETCHINC" "SKPOLY"
                    "SKYSTATUS" "SMASSEMBLYEXPORTREPORTPATHTYPE" "SMASSEMBLYEXPORTSOLIDTYPESINREPORTS" "SMCONVERTMAXIMALBEVELANGLE"
                    "SMCONVERTMINIMALBEVELANGLE" "SMCONVERTPREFERFORMFEATURES" "SMCONVERTPREFERHEMFEATURES" "SMCONVERTPREFERJOGFEATURES"
                    "SMCONVERTPREFERZEROBENDFEATURES" "SMCONVERTRECOGNIZEBEVELS" "SMCONVERTRECOGNIZEHOLES" "SMCONVERTRECOGNIZERIBCONTROLCURVES"
                    "SMCONVERTWRONGFEATURETHICKNESSDEVIATIONTYPE" "SMCONVERTWRONGFEATURETHICKNESSDEVIATIONVALUE" "SMDEFAULTBENDLINEEXTENTTYPE" "SMDEFAULTBENDLINEEXTENTVALUE"
                    "SMDEFAULTBENDRADIUSTYPE" "SMDEFAULTBENDRADIUSVALUE" "SMDEFAULTBENDRELIEFWIDTHTYPE" "SMDEFAULTBENDRELIEFWIDTHVALUE"
                    "SMDEFAULTBEVELFEATUREUNFOLDMODE" "SMDEFAULTCORNERRELIEFDIAMETERVALUE" "SMDEFAULTFLANGESPLITEXTENSIONTYPE" "SMDEFAULTFLANGESPLITEXTENSIONVALUE"
                    "SMDEFAULTFLANGESPLITGAPTYPE" "SMDEFAULTFLANGESPLITGAPVALUE" "SMDEFAULTFORMFEATUREUNFOLDMODE" "SMDEFAULTGUSSETDEPTHTYPE"
                    "SMDEFAULTGUSSETDEPTHVALUE" "SMDEFAULTGUSSETFILLETRADIUSTYPE" "SMDEFAULTGUSSETFILLETRADIUSVALUE" "SMDEFAULTGUSSETTYPE"
                    "SMDEFAULTGUSSETWIDTHTYPE" "SMDEFAULTGUSSETWIDTHVALUE" "SMDEFAULTHEMGAPTYPE" "SMDEFAULTHEMGAPVALUE"
                    "SMDEFAULTHEMRELATIVEBENDDEDUCTION" "SMDEFAULTJOGANGLEVALUE" "SMDEFAULTJOGHEIGHTTYPE" "SMDEFAULTJOGHEIGHTVALUE"
                    "SMDEFAULTJOGRADIUSTYPE" "SMDEFAULTJOGRADIUSVALUE" "SMDEFAULTJUNCTIONALIGNMENTTORELIEF" "SMDEFAULTJUNCTIONGAPTYPE"
                    "SMDEFAULTJUNCTIONGAPVALUE" "SMDEFAULTKFACTOR" "SMDEFAULTLOFTEDBENDNUMBERSAMPLES" "SMDEFAULTRELIEFEXTENSIONTYPE"
                    "SMDEFAULTRELIEFEXTENSIONVALUE" "SMDEFAULTRIBFILLETRADIUSTYPE" "SMDEFAULTRIBFILLETRADIUSVALUE" "SMDEFAULTRIBPROFILERADIUSTYPE"
                    "SMDEFAULTRIBPROFILERADIUSVALUE" "SMDEFAULTRIBROUNDRADIUSTYPE" "SMDEFAULTRIBROUNDRADIUSVALUE" "SMDEFAULTSHARPBENDRADIUSLIMITRATIO"
                    "SMDEFAULTTABCHAMFERDISTANCETYPE" "SMDEFAULTTABCHAMFERDISTANCEVALUE" "SMDEFAULTTABCLEARANCETYPE" "SMDEFAULTTABCLEARANCEVALUE"
                    "SMDEFAULTTABDISTANCETYPE" "SMDEFAULTTABDISTANCEVALUE" "SMDEFAULTTABEDGETYPE" "SMDEFAULTTABFILLETRADIUSTYPE"
                    "SMDEFAULTTABFILLETRADIUSVALUE" "SMDEFAULTTABHEIGHTTYPE" "SMDEFAULTTABHEIGHTVALUE" "SMDEFAULTTABLENGTHTYPE"
                    "SMDEFAULTTABLENGTHVALUE" "SMDEFAULTTABSLOTNUMBER" "SMDEFAULTTHICKNESS" "SMEXPORTOSMAPPROXIMATIONACCURACY"
                    "SMEXPORTOSMMINIMALEDGELENGTH" "SMHEMCREATECLOSEDHEMGAP" "SMJUNCTIONCREATEHEALCOINCIDENT" "SMPARAMETRIZEHOLESPARAMETRIZATION"
                    "SMREPAIRLOFTEDBENDMERGE" "SMSPLITAMBIGUOUSINPUT" "SMSPLITCONVERTBENDTOJUNCTION" "SMSPLITHEALCOINCIDENT"
                    "SMSPLITORTHOGONALBENDSPLIT" "SNAPANG" "SNAPBASE" "SNAPISOPAIR"
                    "SNAPMODE" "SNAPSTYL" "SNAPUNIT" "SOLIDHIST"
                    "SORTENTS" "SPLFRAME" "SPLINESEGS" "SPLINETYPE"
                    "STEPSIZE" "STEPSPERSEC" "STORYBAR" "SUNSTATUS"
                    "SURFTAB1" "SURFTAB2" "SURFTYPE" "SURFU"
                    "SURFV" "TABLELAYER" "TANGENTLENGTHTYPE" "TANGENTLENGTHVALUE"
                    "TARGET" "TDCREATE" "TDINDWG" "TDUCREATE"
                    "TDUPDATE" "TDUSRTIMER" "TDUUPDATE" "TEETANGENTLENGTHTYPE"
                    "TEETANGENTLENGTHVALUE" "TEXTJUSTIFY" "TEXTLAYER" "TEXTSIZE"
                    "TEXTSTYLE" "TEXTTOATTRIBUTE" "THICKNESS" "TILEMODE"
                    "TILEMODELIGHTSYNCH" "TIMEZONE" "TRACEWID" "TREEDEPTH"
                    "TSTACKALIGN" "TSTACKSIZE" "UCSBASE" "UCSFOLLOW"
                    "UCSICON" "UCSNAME" "UCSORG" "UCSVP"
                    "UCSXDIR" "UCSYDIR" "UNITMODE" "UPDATETHUMBNAIL"
                    "USERI1" "USERI2" "USERI3" "USERI4"
                    "USERI5" "USERR1" "USERR2" "USERR3"
                    "USERR4" "USERR5" "VIEWCTR" "VIEWDIR"
                    "VIEWMODE" "VIEWPORTLAYER" "VIEWSIZE" "VIEWTWIST"
                    "VIEWUPDATEAUTO" "VISRETAIN" "VPLAYEROVERRIDES" "VSACURVATUREHIGH"
                    "VSACURVATURELOW" "VSACURVATURETYPE" "VSADRAFTANGLEHIGH" "VSAZEBRACOLOR1"
                    "VSAZEBRACOLOR2" "VSAZEBRADIRECTION" "VSAZEBRASIZE" "VSAZEBRATYPE"
                    "VSBACKGROUNDS" "VSEDGECOLOR" "VSEDGEJITTER" "VSEDGELEX"
                    "VSEDGES" "VSEDGESMOOTH" "VSFACECOLORMODE" "VSFACEHIGHLIGHT"
                    "VSFACEOPACITY" "VSFACESTYLE" "VSHALOGAP" "VSINTERSECTIONCOLOR"
                    "VSINTERSECTIONEDGES" "VSINTERSECTIONLTYPE" "VSISOONTOP" "VSLIGHTINGQUALITY"
                    "VSMATERIALMODE" "VSMAX" "VSMIN" "VSMONOCOLOR"
                    "VSOCCLUDEDCOLOR" "VSOCCLUDEDEDGES" "VSOCCLUDEDLTYPE" "VSSHADOWS"
                    "VSSILHEDGES" "VSSILHWIDTH" "WIPEOUTFRAME" "WORLDVIEW"
                    "XCLIPFRAME" "XEDIT" "XREFLAYER" "XREFOVERRIDE"
                    ))
      (setf (gethash name table) t))
    table)
  "Name -> T for each system variable saved in the drawing (520).")

(defun drawing-saved-sysvar-p (name)
  "True when system variable NAME is saved in the drawing (one per document),
false when it is the application's (registry / preference / session: shared)."
  (values (gethash name *drawing-saved-sysvars*)))

(defparameter *sysvar-scope-tiers*
  (let ((table (make-hash-table :test #'equalp)))
    (loop for (name tier) on '(
                    "3DCONVERSIONMODE" :registry "3DDWFPREC" :drawing "3DOSMODE" :registry
                    "3DSELECTIONMODE" :registry "ACADLSPASDOC" :registry "ACADPREFIX" :not-saved
                    "ACADVER" :not-saved "ACISHLRRESOLUTION" :registry "ACISOUTVER" :not-saved
                    "ACISSAVEASMODE" :registry "ACTIVITYINSIGHTSPATH" :registry "ACTIVITYINSIGHTSSTATE" :not-saved
                    "ACTIVITYINSIGHTSSUPPORT" :registry "ACTIVITYINSIGHTSVIEWEDLOGGING" :registry "ACTPATH" :registry
                    "ACTRECORDERSTATE" :not-saved "ACTRECPATH" :registry "ACTUI" :registry
                    "ADAPTIVEGRIDSTEPSIZE" :registry "ADCSTATE" :not-saved "AFLAGS" :not-saved
                    "ALIGNDIMENSIONONISOMETRIC" :registry "ALLOWEDBENDANGLES" :registry "ALLOWTABEXTERNALMOVE" :registry
                    "ALLOWTABMOVE" :registry "ALLOWTABSPLIT" :registry "AMPOWERDIMDISPLAY" :drawing
                    "AMSYMSCALE" :drawing "ANGBASE" :drawing "ANGDIR" :drawing
                    "ANNOALLVISIBLE" :drawing "ANNOAUTOSCALE" :registry "ANNOMONITOR" :drawing
                    "ANNOSCALEZOOM" :registry "ANNOTATIVEDWG" :drawing "ANTIALIASRENDER" :registry
                    "ANTIALIASSCREEN" :registry "APBOX" :registry "APERTURE" :registry
                    "APPAUTOLOAD" :registry "APPLYGLOBALOPACITIES" :registry "APSTATE" :not-saved
                    "AREA" :not-saved "AREAPREC" :registry "AREAUNITS" :registry
                    "ARRAYASSOCIATIVITY" :registry "ARRAYEDITSTATE" :not-saved "ARRAYTYPE" :registry
                    "ASSISTANTSTATE" :registry "ATTDIA" :registry "ATTFULLUPDATE" :registry
                    "ATTIPE" :registry "ATTMODE" :drawing "ATTMULTI" :registry
                    "ATTRACTIONDISTANCE" :registry "ATTREQ" :registry "AUDITCTL" :registry
                    "AUDITERRORCOUNT" :not-saved "AUNITS" :drawing "AUPREC" :drawing
                    "AUTOCOMPLETEDELAY" :registry "AUTOCOMPLETEMODE" :registry "AUTODWFPUBLISH" :registry
                    "AUTOMATICCONNECTION" :registry "AUTOMATICPUB" :registry "AUTOMATICSTAIRSECTIONBEHAVIOR" :registry
                    "AUTOMATICTEES" :registry "AUTOPLACEMENT" :registry "AUTORESETSCALES" :registry
                    "AUTOSAVECHECKSONLYFIRSTBITDBMOD" :registry "AUTOSNAP" :registry "AUTOTRACKINGVECCOLOR" :registry
                    "AUTOVPFITTING" :registry "BACKGROUNDPLOT" :registry "BACKZ" :drawing
                    "BACTIONBARMODE" :registry "BACTIONCOLOR" :registry "BASEFILE" :registry
                    "BCFSOURCEURL" :registry "BCONSTATUSMODE" :not-saved "BCONVERTLAYER" :registry
                    "BDEPENDENCYHIGHLIGHT" :registry "BEDITASSOCMODE" :registry "BGCOREPUBLISH" :registry
                    "BGRIPOBJCOLOR" :registry "BGRIPOBJSIZE" :registry "BILLOFMATERIALSSETTINGS" :registry
                    "BIMDEFAULTPROPERTIESPATH" :registry "BIMMATCHPROP" :drawing "BIMOSMODE" :registry
                    "BIMPROFILESTANDARDS" :registry "BINDTYPE" :not-saved "BKGCOLOR" :registry
                    "BKGCOLORPS" :registry "BLIPMODE" :registry "BLOCKCREATEMODE" :registry
                    "BLOCKEDITLOCK" :registry "BLOCKEDITOR" :not-saved "BLOCKEXCLUDECOLOR" :registry
                    "BLOCKIFYMODE" :registry "BLOCKIFYTOLERANCE" :registry "BLOCKINCLUDECOLOR" :registry
                    "BLOCKLEVELOFDETAIL" :drawing "BLOCKMRULIST" :registry "BLOCKNAVIGATE" :registry
                    "BLOCKREDEFINEMODE" :registry "BLOCKSDATACOLLECTION" :registry "BLOCKSPATH" :registry
                    "BLOCKSRECENTFOLDER" :registry "BLOCKSTATE" :not-saved "BLOCKSYNCFOLDER" :registry
                    "BLOCKTARGETCOLOR" :registry "BLOCKTESTWINDOW" :not-saved "BMAUTOUPDATE" :registry
                    "BMEXTERNALIZEILLEGALSYMBOLS" :registry "BMFORMTEMPLATEPATH" :registry "BMTOOLPATH" :registry
                    "BMUPDATEMODE" :registry "BOLTINGASMDEFAULTLENGTHINCREMENT" :drawing "BOLTINGASMDEFAULTNUT" :drawing
                    "BOLTINGASMDEFAULTNUTSNUMBER" :drawing "BOLTINGASMDEFAULTSTUD" :drawing "BOMFILTERSETTINGS" :registry
                    "BOMPROPERTYSET" :registry "BOMTEMPLATE" :registry "BOMTHUMBNAILHEIGHT" :registry
                    "BOMTHUMBNAILWIDTH" :registry "BOUNDARYCOLOR" :registry "BPARAMETERCOLOR" :registry
                    "BPARAMETERFONT" :registry "BPARAMETERSIZE" :registry "BPTEXTHORIZONTAL" :registry
                    "BSEARCHINCLUDEEXISTINGBLOCKS" :not-saved "BSYSLIBCOPYOVERWRITE" :registry "BTMARKDISPLAY" :registry
                    "BVMODE" :not-saved "CACHELAYOUT" :registry "CACHEMAXFILES" :registry
                    "CACHEMAXTOTALSIZE" :registry "CALCINPUT" :registry "CAMERADISPLAY" :drawing
                    "CAMERAHEIGHT" :drawing "CANNOSCALE" :drawing "CANNOSCALEVALUE" :drawing
                    "CAPTURETHUMBNAILS" :registry "CBARTRANSPARENCY" :registry "CCONSTRAINTFORM" :registry
                    "CDATE" :not-saved "CECOLOR" :drawing "CELTSCALE" :drawing
                    "CELTYPE" :drawing "CELWEIGHT" :drawing "CENTERCROSSGAP" :drawing
                    "CENTERCROSSSIZE" :drawing "CENTEREXE" :drawing "CENTERLAYER" :drawing
                    "CENTERLTSCALE" :drawing "CENTERLTYPE" :drawing "CENTERLTYPEFILE" :drawing
                    "CENTERMARKEXE" :drawing "CENTERMT" :registry "CETRANSPARENCY" :drawing
                    "CGEOCS" :drawing "CHAMFERA" :drawing "CHAMFERB" :drawing
                    "CHAMFERC" :drawing "CHAMFERD" :drawing "CHAMMODE" :not-saved
                    "CHECKDWLPRESENCE" :registry "CIRCLERAD" :not-saved "CIRCULARARROWHEADLENGTH" :drawing
                    "CIRCULARARROWHEADWIDTH" :drawing "CIRCULARARROWLEADERRADIUS" :drawing "CIRCULARARROWLEADERROTATION" :drawing
                    "CIRCULARARROWTHICKNESS" :drawing "CLAYER" :drawing "CLAYOUT" :drawing
                    "CLEANSCREENOPTIONS" :registry "CLEANSCREENSTATE" :not-saved "CLIPBOARDFORMAT" :registry
                    "CLIPBOARDFORMATS" :registry "CLIPROMPTLINES" :registry "CLIPROMPTUPDATE" :registry
                    "CLISTATE" :not-saved "CLOSECHECKSONLYFIRSTBITDBMOD" :registry "CLOUDDOWNLOADPATH" :registry
                    "CLOUDLOG" :registry "CLOUDLOGVERBOSE" :registry "CLOUDONMODIFIED" :registry
                    "CLOUDSERVER" :registry "CLOUDSSOCLIENTID" :registry "CLOUDSSOSCOPE" :registry
                    "CLOUDTEMPFOLDER" :registry "CLOUDUPLOADDEPENDENCIES" :registry "CMATERIAL" :drawing
                    "CMDACTIVE" :not-saved "CMDDIA" :registry "CMDECHO" :not-saved
                    "CMDINPUTHISTORYMAX" :registry "CMDLINEEDITBGCOLOR" :registry "CMDLINEEDITFGCOLOR" :registry
                    "CMDLINEFADINGLOGBGCOLOR" :registry "CMDLINEFADINGLOGFADEDELAY" :registry "CMDLINEFADINGLOGFGCOLOR" :registry
                    "CMDLINEFADINGLOGTRANSPARENCY" :registry "CMDLINEFONTNAME" :registry "CMDLINEFONTSIZE" :registry
                    "CMDLINEFRAMEACTIVETRANSPARENCY" :registry "CMDLINEFRAMEINACTIVETRANSPARENCY" :registry "CMDLINEFRAMEUSETEXTSCR" :registry
                    "CMDLINELISTBGCOLOR" :registry "CMDLINELISTFGCOLOR" :registry "CMDLINEOPTIONBGCOLOR" :registry
                    "CMDLINEOPTIONSHORTCUTCOLOR" :registry "CMDLINEUSEMINIFRAME" :registry "CMDLNTEXT" :registry
                    "CMDNAMES" :not-saved "CMFADECOLOR" :registry "CMFADEOPACITY" :registry
                    "CMLEADERSTYLE" :drawing "CMLJUST" :drawing "CMLSCALE" :drawing
                    "CMLSTYLE" :drawing "CMOSNAP" :registry "CMPCLRMISS" :registry
                    "CMPCLRMOD1" :registry "CMPCLRMOD2" :registry "CMPCLRNEW" :registry
                    "CMPDIFFLIMIT" :registry "CMPFADECTL" :registry "CMPLOG" :registry
                    "COLORBOOKPATH" :registry "COLORPICKBOX" :registry "COLORTHEME" :registry
                    "COLORX" :registry "COLORY" :registry "COLORZ" :registry
                    "COMACADCOMPATIBILITY" :registry "COMBINETEXTMODE" :registry "COMMANDASSIST" :registry
                    "COMMANDMACROSSTATE" :not-saved "COMMANDPREVIEW" :registry "COMMENTHIGHLIGHT" :registry
                    "COMMUNICATORBACKGROUNDMODE" :registry "COMMUNICATORPATH" :registry "COMPARECOLOR1" :registry
                    "COMPARECOLOR2" :registry "COMPARECOLORCOMMON" :registry "COMPAREFRONT" :drawing
                    "COMPAREHATCH" :drawing "COMPAREPROPS" :registry "COMPARERCMARGIN" :drawing
                    "COMPARERCSHAPE" :drawing "COMPARESHOW1" :drawing "COMPARESHOW2" :drawing
                    "COMPARESHOWCOMMON" :drawing "COMPARESHOWCONTEXT" :drawing "COMPARESHOWRC" :drawing
                    "COMPARETEXT" :drawing "COMPARETOLERANCE" :drawing "COMPASS" :not-saved
                    "COMPLEXLTPREVIEW" :registry "COMPONENTSCONFIG" :not-saved "COMPONENTSPATH" :registry
                    "CONSTRAINTBARDISPLAY" :registry "CONSTRAINTBARMODE" :registry "CONSTRAINTINFER" :registry
                    "CONSTRAINTNAMEFORMAT" :registry "CONSTRAINTSOLVEMODE" :registry "CONTINUOUSMOTION" :registry
                    "CONVERTODMAX" :registry "CONVERTODMIN" :registry "CONVERTTHMAX" :registry
                    "CONVERTTHMIN" :registry "COORDS" :registry "COPYGUIDED3DDISPLAYSOURCEFACES" :registry
                    "COPYMODE" :registry "COUNTCHECK" :registry "COUNTCOLOR" :registry
                    "COUNTERRORCOLOR" :registry "COUNTERRORNUM" :not-saved "COUNTNUMBER" :not-saved
                    "COUNTPALETTESTATE" :not-saved "COUNTSERVICE" :registry "CPLOTSTYLE" :drawing
                    "CPROFILE" :registry "CRASHREPORTSENDING" :registry "CREATESKETCHFEATURE" :registry
                    "CREATETHUMBNAILONTHEFLY" :registry "CREATEVIEWPORTS" :registry "CROSSHAIRDRAWMODE" :registry
                    "CROSSINGAREACOLOR" :registry "CTAB" :drawing "CTABLESTYLE" :drawing
                    "CTRL3DMOUSE" :registry "CTRLMBUTTON" :not-saved "CTRLMOUSE" :registry
                    "CULLINGOBJ" :registry "CULLINGOBJSELECTION" :registry "CURSORBADGE" :registry
                    "CURSORMODE" :not-saved "CURSORSIZE" :registry "CURSORTYPE" :registry
                    "CVALLOWBREAKLINECROSSINGS" :drawing "CVANGLESAMPLINGINTERVAL" :drawing "CVARCTESSELLATIONGRADING" :drawing
                    "CVARCTESSELLATIONSURFACE" :drawing "CVARCTESSELLATIONTEMPLATEELEMENT" :drawing "CVASSOCIATIVITY" :drawing
                    "CVDEFAULTCURVETYPEHA" :drawing "CVDEFAULTCURVETYPEVA" :drawing "CVELEVATIONATBREAKLINECROSSINGS" :drawing
                    "CVERSIONCONTROLPATH" :registry "CVGRADEUNIT" :drawing "CVGRADEUNITPREC" :drawing
                    "CVIEWDETAILSTYLE" :drawing "CVLENGTHSAMPLINGINTERVAL" :drawing "CVPORT" :drawing
                    "CVSLOPEUNIT" :drawing "CVSLOPEUNITPREC" :drawing "CVSTATIONUNIT" :drawing
                    "CVSTATIONUNITPREC" :drawing "DATACOLLECTION" :registry "DATACOLLECTIONENABLED" :not-saved
                    "DATACOLLECTIONLOGINTYPE" :registry "DATACOLLECTIONOPTIONS" :registry "DATALINKNOTIFY" :registry
                    "DATE" :not-saved "DBCSTATE" :drawing "DBLCLKEDIT" :registry
                    "DBMOD" :not-saved "DCTCUST" :registry "DCTMAIN" :registry
                    "DEFAULTBSYSLIBIMPERIAL" :registry "DEFAULTBSYSLIBMETRIC" :registry "DEFAULTGIZMO" :not-saved
                    "DEFAULTLIGHTING" :drawing "DEFAULTLIGHTINGTYPE" :drawing "DEFAULTLIGHTSHADOWBLUR" :registry
                    "DEFAULTNEWSHEETTEMPLATE" :registry "DEFAULTPLOTSTYLETABLE" :registry "DEFAULTSPACEHEIGHT" :drawing
                    "DEFAULTSTORYNAMINGSCHEME" :not-saved "DEFAULTSTYLEPIPECROSS" :registry "DEFAULTSTYLEPIPEECCENTRICREDUCER" :registry
                    "DEFAULTSTYLEPIPEELBOW45" :registry "DEFAULTSTYLEPIPEELBOW90" :registry "DEFAULTSTYLEPIPEREDUCER" :registry
                    "DEFAULTSTYLEPIPESEGMENT" :registry "DEFAULTSTYLEPIPETEE" :registry "DEFLPLSTYLE" :registry
                    "DEFPLSTYLE" :registry "DELETETOOL" :not-saved "DELOBJ" :registry
                    "DEMANDLOAD" :registry "DETAILSPATH" :registry "DGNEXPXREFMODE" :registry
                    "DGNFRAME" :drawing "DGNIMP2DCLOSEDBSPLINECURVEIMPORTMODE" :registry "DGNIMP2DELLIPSEIMPORTMODE" :registry
                    "DGNIMP2DSHAPEIMPORTMODE" :registry "DGNIMP3DCLOSEDBSPLINECURVEIMPORTMODE" :registry "DGNIMP3DELLIPSEIMPORTMODE" :registry
                    "DGNIMP3DOBJECTIMPORTMODE" :registry "DGNIMP3DSHAPEIMPORTMODE" :registry "DGNIMPBREAKDIMENSIONASSOCIATION" :registry
                    "DGNIMPCONVERTDGNCOLORINDICESTOTRUECOLORS" :registry "DGNIMPCONVERTEMPTYDATAFIELDSTOSPACES" :registry "DGNIMPERASEUNUSEDRESOURCES" :registry
                    "DGNIMPEXPLODETEXTNODES" :registry "DGNIMPIMPORTACTIVEMODELTOMODELSPACE" :registry "DGNIMPIMPORTDGTEXTSASDBMTEXTS" :registry
                    "DGNIMPIMPORTINVISIBLEELEMENTS" :registry "DGNIMPIMPORTPAPERSPACEMODELS" :registry "DGNIMPIMPORTVIEWINDEX" :registry
                    "DGNIMPORTMAX" :registry "DGNIMPORTMODE" :registry "DGNIMPRECOMPUTEDIMENSIONSAFTERIMPORT" :registry
                    "DGNIMPSYMBOLRESOURCEFILES" :registry "DGNIMPXREFIMPORTMODE" :registry "DGNMAPPINGPATH" :registry
                    "DGNOSNAP" :registry "DIASTAT" :not-saved "DIMADEC" :drawing
                    "DIMALT" :drawing "DIMALTD" :drawing "DIMALTF" :drawing
                    "DIMALTRND" :drawing "DIMALTTD" :drawing "DIMALTTZ" :drawing
                    "DIMALTU" :drawing "DIMALTZ" :drawing "DIMANNO" :drawing
                    "DIMAPOST" :drawing "DIMARCSYM" :drawing "DIMASO" :drawing
                    "DIMASSOC" :drawing "DIMASZ" :drawing "DIMATFIT" :drawing
                    "DIMAUNIT" :drawing "DIMAZIN" :drawing "DIMBLK" :drawing
                    "DIMBLK1" :drawing "DIMBLK2" :drawing "DIMCEN" :drawing
                    "DIMCLRD" :drawing "DIMCLRE" :drawing "DIMCLRT" :drawing
                    "DIMCONSTRAINTICON" :registry "DIMCONTINUEMODE" :registry "DIMDEC" :drawing
                    "DIMDLE" :drawing "DIMDLI" :drawing "DIMDSEP" :drawing
                    "DIMEXE" :drawing "DIMEXO" :drawing "DIMFIT" :drawing
                    "DIMFRAC" :drawing "DIMFXL" :drawing "DIMFXLON" :drawing
                    "DIMGAP" :drawing "DIMJOGANG" :drawing "DIMJUST" :drawing
                    "DIMLAYER" :drawing "DIMLDRBLK" :drawing "DIMLFAC" :drawing
                    "DIMLIM" :drawing "DIMLTEX1" :drawing "DIMLTEX2" :drawing
                    "DIMLTYPE" :drawing "DIMLUNIT" :drawing "DIMLWD" :drawing
                    "DIMLWE" :drawing "DIMMARKTYPE" :drawing "DIMPICKBOX" :registry
                    "DIMPOST" :drawing "DIMRND" :drawing "DIMSAH" :drawing
                    "DIMSCALE" :drawing "DIMSD1" :drawing "DIMSD2" :drawing
                    "DIMSE1" :drawing "DIMSE2" :drawing "DIMSHO" :drawing
                    "DIMSOXD" :drawing "DIMSTYLE" :drawing "DIMTAD" :drawing
                    "DIMTDEC" :drawing "DIMTFAC" :drawing "DIMTFILL" :drawing
                    "DIMTFILLCLR" :drawing "DIMTIH" :drawing "DIMTIX" :drawing
                    "DIMTM" :drawing "DIMTMOVE" :drawing "DIMTOFL" :drawing
                    "DIMTOH" :drawing "DIMTOL" :drawing "DIMTOLJ" :drawing
                    "DIMTP" :drawing "DIMTSZ" :drawing "DIMTVP" :drawing
                    "DIMTXSTY" :drawing "DIMTXT" :drawing "DIMTXTDIRECTION" :drawing
                    "DIMTXTRULER" :registry "DIMTZIN" :drawing "DIMUNIT" :drawing
                    "DIMUPT" :drawing "DIMZIN" :drawing "DISPLAYAXES" :drawing
                    "DISPLAYAXESFORMEP" :registry "DISPLAYSCALING" :not-saved "DISPLAYSIDESANDENDS" :drawing
                    "DISPLAYSNAPMARKERINALLVIEWS" :registry "DISPLAYTOOLTIPS" :registry "DISPLAYTRUEDIMENSION" :registry
                    "DISPPAPERBKG" :registry "DISPPAPERMARGINS" :registry "DISPSILH" :drawing
                    "DISPSILHBLOCKS" :registry "DISTANCE" :not-saved "DIVMESHBOXHEIGHT" :registry
                    "DIVMESHBOXLENGTH" :registry "DIVMESHBOXWIDTH" :registry "DIVMESHCONEAXIS" :registry
                    "DIVMESHCONEBASE" :registry "DIVMESHCONEHEIGHT" :registry "DIVMESHCYLAXIS" :registry
                    "DIVMESHCYLBASE" :registry "DIVMESHCYLHEIGHT" :registry "DIVMESHPYRBASE" :registry
                    "DIVMESHPYRHEIGHT" :registry "DIVMESHPYRLENGTH" :registry "DIVMESHSPHEREAXIS" :registry
                    "DIVMESHSPHEREHEIGHT" :registry "DIVMESHTORUSPATH" :registry "DIVMESHTORUSSECTION" :registry
                    "DIVMESHWEDGEBASE" :registry "DIVMESHWEDGEHEIGHT" :registry "DIVMESHWEDGELENGTH" :registry
                    "DIVMESHWEDGESLOPE" :registry "DIVMESHWEDGEWIDTH" :registry "DMAUDITLEVEL" :not-saved
                    "DMAUTOUPDATE" :registry "DMCONNECTIONCUTTYPE" :registry "DMPUSHPULLSUBTRACT" :not-saved
                    "DMRECOGNIZE" :drawing "DOCKPRIORITY" :registry "DOCTABPOSITION" :registry
                    "DONUTID" :not-saved "DONUTOD" :not-saved "DRAGMODE" :registry
                    "DRAGMODECONSTRAINTS" :registry "DRAGMODEFACES" :not-saved "DRAGMODEHIDE" :registry
                    "DRAGMODEINTERRUPT" :registry "DRAGOPEN" :registry "DRAGP1" :registry
                    "DRAGP2" :registry "DRAGSNAP" :registry "DRAGVS" :drawing
                    "DRAWINGPATH" :registry "DRAWINGVIEWASM" :registry "DRAWINGVIEWENTS" :drawing
                    "DRAWINGVIEWFLAGS" :registry "DRAWINGVIEWPRESET" :registry "DRAWINGVIEWPRESETHIDDEN" :registry
                    "DRAWINGVIEWPRESETSCALE" :registry "DRAWINGVIEWPRESETTANGENT" :registry "DRAWINGVIEWPRESETTRAILING" :registry
                    "DRAWINGVIEWQUALITY" :drawing "DRAWORDERCTL" :drawing "DRSTATE" :not-saved
                    "DWFFORMAT" :registry "DWFFRAME" :drawing "DWFOSNAP" :registry
                    "DWFVERSION" :registry "DWGCHECK" :registry "DWGCODEPAGE" :not-saved
                    "DWGGUIDCLOUDAI" :drawing "DWGNAME" :not-saved "DWGPREFIX" :not-saved
                    "DWGTITLED" :not-saved "DX12FRAMERATEUNLIMITED" :registry "DXEVAL" :drawing
                    "DXFTEXTADJUSTALIGNMENT" :registry "DYNCONSTRAINTMODE" :registry "DYNDIGRIP" :registry
                    "DYNDIMAPERTURE" :registry "DYNDIMCOLORHOT" :registry "DYNDIMCOLORHOVER" :registry
                    "DYNDIMDISTANCE" :registry "DYNDIMLINETYPE" :registry "DYNDIVIS" :registry
                    "DYNINFOTIPS" :registry "DYNINPUTTRANSPARENCY" :registry "DYNMODE" :registry
                    "DYNPICOORDS" :registry "DYNPIFORMAT" :registry "DYNPIVIS" :registry
                    "DYNPROMPT" :registry "DYNTOOLTIPS" :registry "EDGEMODE" :registry
                    "ELEVATION" :drawing "ENABLEATTRACTION" :registry "ENABLEBIMBKUPDATE" :registry
                    "ENABLEHYPERLINKMENU" :registry "ENABLEHYPERLINKTOOLTIP" :registry "ENABLESYNCPDF" :registry
                    "ENTERPRISEMENU" :registry "ERHIGHLIGHT" :registry "ERRNO" :not-saved
                    "ERSTATE" :not-saved "EXPERIMENTALMODE" :registry "EXPERIMENTALONSTARTPAGE" :registry
                    "EXPERT" :not-saved "EXPINSALIGN" :registry "EXPINSANGLE" :registry
                    "EXPINSFIXANGLE" :registry "EXPINSFIXSCALE" :registry "EXPINSSCALE" :registry
                    "EXPLMODE" :not-saved "EXPORT3DPDFWRITER" :registry "EXPORTACISASSEMBLYWRITER" :registry
                    "EXPORTACISFORMATVERSION" :registry "EXPORTCATIAV4FORMATVERSION" :registry "EXPORTCATIAV5FORMATVERSION" :registry
                    "EXPORTEPLOTFORMAT" :registry "EXPORTGEOMETRYFLAGS" :registry "EXPORTHIDDENPARTS" :registry
                    "EXPORTMODELSPACE" :drawing "EXPORTPAGESETUP" :drawing "EXPORTPAPERSPACE" :drawing
                    "EXPORTPARASOLIDFORMATVERSION" :registry "EXPORTPRODUCTSTRUCTURE" :registry "EXPORTSTEPFORMATVERSION" :registry
                    "EXPORTXCGMFORMATVERSION" :registry "EXPVALUE" :drawing "EXPWHITEBALANCE" :drawing
                    "EXTMAX" :drawing "EXTMIN" :drawing "EXTNAMES" :drawing
                    "EXTRUDEINSIDE" :not-saved "EXTRUDEOUTSIDE" :not-saved "FACETERDEVNORMAL" :registry
                    "FACETERDEVSURFACE" :registry "FACETERMAXEDGELENGTH" :registry "FACETERMAXGRID" :registry
                    "FACETERMESHTYPE" :registry "FACETERMINVGRID" :registry "FACETERPRIMITIVEMODE" :registry
                    "FACETERSMOOTHLEV" :registry "FACETRATIO" :not-saved "FACETRES" :drawing
                    "FASTSHADEDMODE" :registry "FBXEXPORTCAMERAS" :registry "FBXEXPORTENTITIES" :registry
                    "FBXEXPORTENTITIESSELTYPE" :registry "FBXEXPORTLIGHTS" :registry "FBXEXPORTMATERIALS" :registry
                    "FBXEXPORTTEXTURES" :registry "FBXEXPORTTEXTURESPATH" :registry "FEATURECOLORS" :registry
                    "FIELDDISPLAY" :registry "FIELDEVAL" :drawing "FILEDIA" :registry
                    "FILETABPREVIEW" :registry "FILETABSTATE" :registry "FILETABTHUMBHOVER" :registry
                    "FILLETPOLYARC" :registry "FILLETRAD" :drawing "FILLETWELDINGCOMBINEADJACENT" :drawing
                    "FILLETWELDINGMAXGAPRATIO" :drawing "FILLETWELDINGZSIZE" :drawing "FILLMODE" :drawing
                    "FITLINEFITARCMODE" :registry "FITTINGRADIUSTYPE" :drawing "FITTINGRADIUSVALUE" :drawing
                    "FLANGEASMDEFAULTGASKET" :drawing "FONTALT" :registry "FONTMAP" :registry
                    "FRAME" :drawing "FRAMESELECTION" :registry "FRONTZ" :drawing
                    "FULLOPEN" :not-saved "FULLPLOTPATH" :registry "GALLERYVIEW" :registry
                    "GEARTEETHNUMBER" :registry "GENERATEASSOCATTRS" :not-saved "GENERATEASSOCVIEWS" :not-saved
                    "GEOCSMAPPRIORITY" :not-saved "GEOLATLONGFORMAT" :registry "GEOLOCATEMODE" :not-saved
                    "GEOMAPMODE" :drawing "GEOMARKERVISIBILITY" :drawing "GEOMARKPOSITIONSIZE" :drawing
                    "GEOMRELATIONS" :registry "GETSTARTED" :registry "GFANG" :not-saved
                    "GFCLR1" :not-saved "GFCLR2" :not-saved "GFCLRLUM" :not-saved
                    "GFCLRSTATE" :not-saved "GFNAME" :not-saved "GFSHIFT" :not-saved
                    "GLOBALOPACITY" :registry "GLSWAPMODE" :registry "GRADIENTCOLORBOTTOM" :registry
                    "GRADIENTCOLORMIDDLE" :registry "GRADIENTCOLORTOP" :registry "GRADIENTMODE" :registry
                    "GRIDAXISCOLOR" :registry "GRIDDISPLAY" :drawing "GRIDMAJOR" :drawing
                    "GRIDMAJORCOLOR" :registry "GRIDMINORCOLOR" :registry "GRIDMODE" :drawing
                    "GRIDSTYLE" :registry "GRIDUNIT" :drawing "GRIDXYZTINT" :registry
                    "GRIPBLOCK" :registry "GRIPCOLOR" :registry "GRIPCONTOUR" :registry
                    "GRIPDYNCOLOR" :registry "GRIPHOT" :registry "GRIPHOVER" :registry
                    "GRIPMULTIFUNCTIONAL" :registry "GRIPOBJLIMIT" :registry "GRIPS" :registry
                    "GRIPSIZE" :registry "GRIPSUBOBJMODE" :registry "GRIPTIPS" :registry
                    "GROUPDISPLAYMODE" :registry "GSDEVICETYPE2D" :registry "GSDEVICETYPE3D" :registry
                    "GTAUTO" :registry "GTDEFAULT" :registry "GTLOCATION" :registry
                    "HALOGAP" :drawing "HANDLES" :drawing "HANDSEED" :not-saved
                    "HELPPREFIX" :registry "HIDEPRECISION" :not-saved "HIDESYSTEMPRINTERS" :registry
                    "HIDETEXT" :drawing "HIDEXREFSCALES" :not-saved "HIGHLIGHT" :not-saved
                    "HIGHLIGHTCOLOR" :registry "HIGHLIGHTEFFECT" :registry "HIGHLIGHT_ALPHA" :registry
                    "HORIZONBKG_ENABLE" :registry "HORIZONBKG_GROUNDHORIZON" :registry "HORIZONBKG_GROUNDORIGIN" :registry
                    "HORIZONBKG_SKYHIGH" :registry "HORIZONBKG_SKYHORIZON" :registry "HORIZONBKG_SKYLOW" :registry
                    "HOTKEYASSISTANT" :registry "HPANG" :not-saved "HPANNOTATIVE" :not-saved
                    "HPASSOC" :registry "HPBACKGROUNDCOLOR" :drawing "HPBOUND" :not-saved
                    "HPBOUNDRETAIN" :not-saved "HPCOLOR" :drawing "HPDLGMODE" :registry
                    "HPDOUBLE" :not-saved "HPDRAWMODE" :registry "HPDRAWORDER" :not-saved
                    "HPGAPTOL" :registry "HPISLANDDETECTION" :not-saved "HPISLANDDETECTIONMODE" :not-saved
                    "HPLAYER" :drawing "HPLINETYPE" :registry "HPMAXAREAS" :registry
                    "HPMAXCONTOURPOINTS" :registry "HPMAXLINES" :registry "HPNAME" :not-saved
                    "HPOBJWARNING" :registry "HPORIGIN" :drawing "HPORIGINMODE" :registry
                    "HPPATHALIGNMENT" :registry "HPPATHWIDTH" :registry "HPPICKMODE" :registry
                    "HPQUICKPREVIEW" :registry "HPQUICKPREVTIMEOUT" :registry "HPSCALE" :not-saved
                    "HPSEPARATE" :registry "HPSPACE" :not-saved "HPTRANSPARENCY" :drawing
                    "HYPERLINKBASE" :drawing "IBLENVIRONMENT" :drawing "IFCCREATEUNIQUEGUID" :registry
                    "IFCEXPLODEEXTERNALREFERENCES" :registry "IFCEXPORTAUTHOR" :registry "IFCEXPORTAUTHORIZATION" :registry
                    "IFCEXPORTBASEQUANTITIES" :registry "IFCEXPORTELEMENTSONOFFANDFROZENLAYER" :registry "IFCEXPORTIDSPROPERTIESONLY" :registry
                    "IFCEXPORTMAPPINGPATH" :registry "IFCEXPORTMULTIPLYELEMENTSASAGGREGATED" :registry "IFCEXPORTORGANIZATION" :registry
                    "IFCEXPORTPROFILECENTEROFGRAVITY" :registry "IFCEXPORTSUBTRACTOPENINGS" :registry "IFCEXPORTSWEPTSOLIDSASBREP" :registry
                    "IFCEXPORTTESSELATION" :registry "IFCEXPORTVALIDATEMODEL" :registry "IFCSETTINGSCONFIG" :not-saved
                    "IFCTESSELATEBSPLINECURVESANDSURFACES" :registry "IMAGEASYNC" :registry "IMAGECACHEFOLDER" :registry
                    "IMAGECACHEMAXMEMORY" :registry "IMAGEDISKCACHE" :registry "IMAGEFRAME" :drawing
                    "IMAGEHLT" :registry "IMAGENOTIFY" :registry "IMPLIEDFACE" :registry
                    "IMPORTCATIAV5EDGEATTRIBUTES" :registry "IMPORTCATIAV5REPRESENTATION" :registry "IMPORTCATIAV5SEARCHPATHSPREFERENCE" :registry
                    "IMPORTCOLORS" :registry "IMPORTCREOALTERNATESEARCHPATHS" :registry "IMPORTCREOCONFIGURATION" :registry
                    "IMPORTCUIFILEEXISTS" :registry "IMPORTHIDDENPARTS" :registry "IMPORTIGESSIMPLIFY" :registry
                    "IMPORTIGESSTITCH" :registry "IMPORTINVENTORALTERNATESEARCHPATHS" :registry "IMPORTINVENTORSEARCHPATHSPREFERENCE" :registry
                    "IMPORTJTREPRESENTATION" :registry "IMPORTNXALTERNATESEARCHPATHS" :registry "IMPORTNXCONFIGURATION" :registry
                    "IMPORTNXSEARCHPATHSPREFERENCE" :registry "IMPORTPMI" :registry "IMPORTPRODUCTSTRUCTURE" :registry
                    "IMPORTREPAIR" :registry "IMPORTSIMPLIFY" :registry "IMPORTSOLIDEDGEALTERNATESEARCHPATHS" :registry
                    "IMPORTSOLIDEDGESEARCHPATHSPREFERENCE" :registry "IMPORTSOLIDWORKSALTERNATESEARCHPATHS" :registry "IMPORTSOLIDWORKSCONFIGURATION" :registry
                    "IMPORTSOLIDWORKSREPRESENTATION" :registry "IMPORTSOLIDWORKSROTATEYZ" :registry "IMPORTSOLIDWORKSSEARCHPATHSPREFERENCE" :registry
                    "IMPORTSTEPROTATEYZ" :registry "IMPORTSTITCH" :registry "INCLUDEPLOTSTAMP" :registry
                    "INDEXCTL" :drawing "INETLOCATION" :registry "INPUTHISTORYMODE" :registry
                    "INPUTSEARCHDELAY" :registry "INSBASE" :drawing "INSNAME" :not-saved
                    "INSUNITS" :drawing "INSUNITSDEFSOURCE" :registry "INSUNITSDEFTARGET" :registry
                    "INSUNITSSCALING" :registry "INTELLIGENTUPDATE" :registry "INTERFERECOLOR" :drawing
                    "INTERFERELAYER" :registry "INTERFERENCELEVEL" :registry "INTERFEREOBJVS" :drawing
                    "INTERFEREVPVS" :drawing "INTERIORELEVATIONMINLENGTH" :drawing "INTERIORELEVATIONOFFSET" :drawing
                    "INTERSECTEDENTITIES" :not-saved "INTERSECTIONCOLOR" :drawing "INTERSECTIONDISPLAY" :drawing
                    "ISAVEBAK" :registry "ISAVEPERCENT" :registry "ISOLINES" :drawing
                    "JIGZOOMMAX" :registry "JIGZOOMMIN" :registry "KEEPCONNECTIONS" :registry
                    "LARGEOBJECTSUPPORT" :registry "LASTANGLE" :not-saved "LASTPOINT" :not-saved
                    "LASTPROMPT" :not-saved "LATITUDE" :drawing "LAYERDLGMODE" :registry
                    "LAYEREVAL" :drawing "LAYEREVALCTL" :registry "LAYERFILTERALERT" :registry
                    "LAYERFILTEREXCESS" :registry "LAYERMANAGERSTATE" :not-saved "LAYERNOTIFY" :drawing
                    "LAYEROVERRIDEHIGHLIGHT" :registry "LAYERPMODE" :registry "LAYLOCKFADECTL" :registry
                    "LAYOUTCREATEVIEWPORT" :registry "LAYOUTREGENCTL" :registry "LAYOUTTAB" :registry
                    "LEGACYCODESEARCH" :registry "LEGACYCTRLPICK" :registry "LENGTHUNITS" :registry
                    "LENSLENGTH" :drawing "LEVELOFDETAIL" :drawing "LICFLAGS" :not-saved
                    "LIGHTGLYPHCOLOR" :registry "LIGHTGLYPHDISPLAY" :drawing "LIGHTINGUNITS" :drawing
                    "LIGHTSINBLOCKS" :drawing "LIGHTWEBGLYPHCOLOR" :registry "LIMCHECK" :drawing
                    "LIMMAX" :drawing "LIMMIN" :drawing "LINEARARROWHEADLENGTH" :drawing
                    "LINEARARROWHEADWIDTH" :drawing "LINEARARROWTHICKNESS" :drawing "LINEARBRIGHTNESS" :drawing
                    "LINEARCONTRAST" :drawing "LINEFADING" :registry "LINEFADINGLEVEL" :registry
                    "LINETYPE3DPLINE" :registry "LISPINIT" :registry "LISPSYS" :registry
                    "LOADMECHANICAL2D" :registry "LOCALE" :not-saved "LOCALROOTPREFIX" :registry
                    "LOCKUI" :registry "LOFTANG1" :drawing "LOFTANG2" :drawing
                    "LOFTMAG1" :drawing "LOFTMAG2" :drawing "LOFTNORMALS" :drawing
                    "LOFTPARAM" :drawing "LOGFILEMODE" :registry "LOGFILENAME" :drawing
                    "LOGFILEPATH" :registry "LOGGEDINSTATUS" :registry "LOGINNAME" :not-saved
                    "LONGITUDE" :drawing "LOOKFROMDIRECTIONMODE" :registry "LOOKFROMFEEDBACK" :registry
                    "LOOKFROMZOOMEXTENTS" :registry "LTGAPSELECTION" :registry "LTSCALE" :drawing
                    "LUNITS" :drawing "LUPREC" :drawing "LWDEFAULT" :registry
                    "LWDISPLAY" :drawing "LWDISPSCALE" :registry "LWUNITS" :registry
                    "MACROINSIGHTSSUPPORT" :registry "MACRONOTIFY" :registry "MACROREC" :not-saved
                    "MANIPULATOR" :registry "MANIPULATORCOLORTHEME" :registry "MANIPULATORDURATION" :registry
                    "MANIPULATORHANDLE" :registry "MANIPULATORSIZE" :registry "MARKUPASSISTMODE" :registry
                    "MARKUPPAPERDISPLAY" :registry "MARKUPPAPERTRANSPARENCY" :registry "MARKUPSELECTIONMODE" :registry
                    "MASSPREC" :registry "MASSPROPACCURACY" :registry "MASSUNITS" :registry
                    "MATBROWSERSTATE" :registry "MATEDITORSTATE" :registry "MAXACTVP" :drawing
                    "MAXHATCH" :registry "MAXINTERSECTIONCURVEPOINTS" :registry "MAXSORT" :registry
                    "MAXTHREADS" :registry "MBSTATE" :not-saved "MBUTTONPAN" :registry
                    "MEASUREINIT" :registry "MEASUREMENT" :drawing "MECH2DSAVEFORMAT" :registry
                    "MECHANICALBLOCKS" :registry "MECHANICALBLOCKSOPTIONS" :registry "MECHANICALBROWSERSETTINGS" :registry
                    "MENUBAR" :registry "MENUCTL" :registry "MENUECHO" :not-saved
                    "MENUNAME" :registry "MESHTYPE" :drawing "MIDDLECLICKCLOSE" :registry
                    "MILLISECS" :not-saved "MIRRHATCH" :drawing "MIRRTEXT" :drawing
                    "MLEADERLAYER" :drawing "MLEADERSCALE" :drawing "MODEMACRO" :not-saved
                    "MSLTSCALE" :drawing "MSMSTATE" :not-saved "MSOLESCALE" :drawing
                    "MTEXTAUTOSTACK" :registry "MTEXTCOLUMN" :registry "MTEXTDETECTSPACE" :registry
                    "MTEXTED" :registry "MTEXTEDENCODING" :registry "MTEXTFIXED" :registry
                    "MTEXTTOOLBAR" :registry "MTFLAGS" :registry "MTJIGSTRING" :registry
                    "MULTISELECTANGULARTOLERANCE" :registry "MVIEWPREVIEW" :registry "MYDOCUMENTSPREFIX" :registry
                    "NAVBARDISPLAY" :registry "NAVSWHEELMODE" :registry "NAVSWHEELOPACITYBIG" :registry
                    "NAVSWHEELOPACITYMINI" :registry "NAVSWHEELSIZEBIG" :registry "NAVSWHEELSIZEMINI" :registry
                    "NAVVCUBEDISPLAY" :drawing "NAVVCUBELOCATION" :registry "NAVVCUBEOPACITY" :registry
                    "NAVVCUBEORIENT" :registry "NAVVCUBESIZE" :registry "NEARESTDISTANCE" :registry
                    "NOMUTT" :not-saved "NORTHDIRECTION" :drawing "OBJECTISOLATIONMODE" :registry
                    "OBSCUREDCOLOR" :drawing "OBSCUREDLTYPE" :drawing "OFFSETDIST" :not-saved
                    "OFFSETERASE" :registry "OFFSETGAPTYPE" :registry "OLEFRAME" :drawing
                    "OLEHIDE" :registry "OLEQUALITY" :registry "OLESTARTUP" :drawing
                    "OPMSTATE" :not-saved "ORBITAUTOTARGET" :registry "ORTHOMODE" :drawing
                    "OSMODE" :registry "OSNAPCOORD" :registry "OSNAPNODELEGACY" :registry
                    "OSNAPOVERRIDE" :not-saved "OSNAPZ" :not-saved "OSOPTIONS" :registry
                    "OVERKILLLAYER" :registry "PALETTEOPAQUE" :registry "PANBUFFER" :registry
                    "PANELBUTTONSIZE" :not-saved "PAPERUPDATE" :registry "PARAMETERCOPYMODE" :registry
                    "PARAMETERMATCHMODE" :not-saved "PARAMETERSSTATUS" :registry "PARAMETRICBLOCKS2DPATH" :registry
                    "PARAMETRIZECONNECTIONS" :registry "PASTESPECMODE" :registry "PBLOCKREFERENCEOPERATIONSVISUALIZATION" :registry
                    "PCMSTATE" :registry "PDFANIMATIONFPS" :registry "PDFCACHE" :registry
                    "PDFCREATEBOOKMARKS" :registry "PDFEMBEDDEDTTF" :registry "PDFEXPORTHYPERLINKS" :registry
                    "PDFFRAME" :drawing "PDFIMAGEANTIALIAS" :registry "PDFIMAGECOMPRESSION" :registry
                    "PDFIMAGEDPI" :registry "PDFIMPORTAPPLYLINEWEIGHT" :registry "PDFIMPORTASBLOCK" :registry
                    "PDFIMPORTCHARSPACEFACTOR" :registry "PDFIMPORTCOMBINETEXTOBJECTS" :registry "PDFIMPORTCONVERTSOLIDSTOHATCHES" :registry
                    "PDFIMPORTFILTER" :registry "PDFIMPORTIMAGEPATH" :registry "PDFIMPORTJOINLINEANDARCSEGMENTS" :registry
                    "PDFIMPORTLAYERS" :registry "PDFIMPORTLAYERSUSETYPE" :registry "PDFIMPORTMODE" :registry
                    "PDFIMPORTRASTERIMAGES" :registry "PDFIMPORTSOLIDFILLS" :registry "PDFIMPORTSPACEFACTOR" :registry
                    "PDFIMPORTTRUETYPETEXT" :registry "PDFIMPORTTRUETYPETEXTASGEOMETRY" :registry "PDFIMPORTUSECLIPPING" :registry
                    "PDFIMPORTUSEGEOMETRYOPTIMIZATION" :registry "PDFIMPORTUSEIMAGECLIPPING" :registry "PDFIMPORTUSEPAGEBORDERCLIPPING" :registry
                    "PDFIMPORTVECTORGEOMETRY" :registry "PDFLAYERSSETTING" :registry "PDFLAYOUTSTOEXPORT" :registry
                    "PDFMERGECONTROL" :registry "PDFNOTIFY" :registry "PDFOPENINVIEWER" :not-saved
                    "PDFOSNAP" :registry "PDFPAPERHEIGHT" :registry "PDFPAPERSIZEOVERRIDE" :registry
                    "PDFPAPERWIDTH" :registry "PDFPDFA" :registry "PDFPRCCOMPRESSION" :registry
                    "PDFPRCEXPORT" :registry "PDFPRCPROJECTION" :registry "PDFPRCVIEWMODE" :registry
                    "PDFSHX" :registry "PDFSHXBESTFONT" :registry "PDFSHXLAYER" :registry
                    "PDFSHXTEXTASGEOMETRY" :registry "PDFSHXTHRESHOLD" :registry "PDFSIMPLEGEOMOPTIMIZATION" :registry
                    "PDFTTFTEXTASGEOMETRY" :registry "PDFUSEPLOTSTYLES" :registry "PDFVECTORRESOLUTIONDPI" :registry
                    "PDFZOOMTOEXTENTSMODE" :registry "PDMODE" :drawing "PDSIZE" :drawing
                    "PEDITACCEPT" :registry "PELLIPSE" :drawing "PERIMETER" :not-saved
                    "PERSPECTIVE" :drawing "PERSPECTIVECLIP" :registry "PFACEVMAX" :not-saved
                    "PICKADD" :registry "PICKAUTO" :registry "PICKBOX" :registry
                    "PICKDRAG" :registry "PICKFIRST" :registry "PICKSTYLE" :registry
                    "PICTUREEXPORTSCALE" :registry "PLACEMENTSWITCH" :not-saved "PLACESBARFOLDER1" :registry
                    "PLACESBARFOLDER2" :registry "PLACESBARFOLDER3" :registry "PLACESBARFOLDER4" :registry
                    "PLATFORM" :not-saved "PLINECACHE" :registry "PLINECONVERTMODE" :registry
                    "PLINEGCENMAX" :registry "PLINEGEN" :drawing "PLINEREVERSEWIDTHS" :registry
                    "PLINETYPE" :registry "PLINEWID" :drawing "PLOTCFGPATH" :registry
                    "PLOTID" :registry "PLOTOFFSET" :registry "PLOTOUTPUTPATH" :registry
                    "PLOTROTMODE" :registry "PLOTSTYLEPATH" :registry "PLOTTER" :registry
                    "PLOTTRANSPARENCYOVERRIDE" :registry "PLQUIET" :registry "POINTCLOUD2DVSDISPLAY" :registry
                    "POINTCLOUDADAPTIVEDISPLAY" :registry "POINTCLOUDAUTOUPDATE" :registry "POINTCLOUDBOUNDARY" :registry
                    "POINTCLOUDCACHEFOLDER" :registry "POINTCLOUDCACHESIZE" :registry "POINTCLOUDCLIPFRAME" :drawing
                    "POINTCLOUDDENSITY" :registry "POINTCLOUDDOLLHOUSE" :registry "POINTCLOUDEYEDOMELIGHTING" :not-saved
                    "POINTCLOUDGAPFILLING" :not-saved "POINTCLOUDHSPC" :registry "POINTCLOUDIGNOREGEOTAGS" :registry
                    "POINTCLOUDLIGHTING" :drawing "POINTCLOUDLIGHTSOURCE" :drawing "POINTCLOUDLOCK" :registry
                    "POINTCLOUDLOD" :drawing "POINTCLOUDNORMALS" :registry "POINTCLOUDPOINTMAX" :registry
                    "POINTCLOUDPOINTMAXLEGACY" :registry "POINTCLOUDPOINTSIZE" :drawing "POINTCLOUDRTDENSITY" :registry
                    "POINTCLOUDSHADING" :drawing "POINTCLOUDVISRETAIN" :drawing "POLARADDANG" :registry
                    "POLARANG" :registry "POLARDIST" :registry "POLARMODE" :registry
                    "POLYSIDES" :not-saved "POPERATIONSCOLOR" :registry "POPUPS" :not-saved
                    "PREVIEWCREATIONTRANSPARENCY" :registry "PREVIEWDELAY" :registry "PREVIEWEFFECT" :registry
                    "PREVIEWFILTER" :registry "PREVIEWTYPE" :drawing "PREVIEWWNDINOPENDLG" :registry
                    "PRINTFILE" :registry "PRINTPDFPREVIEW" :registry "PRODUCT" :not-saved
                    "PROFILEOFFSETBEHAVIOR" :registry "PROGBAR" :not-saved "PROGRAM" :not-saved
                    "PROJECTAWARE" :not-saved "PROJECTIONTYPE" :drawing "PROJECTLOCATIONVISIBILITY" :drawing
                    "PROJECTNAME" :drawing "PROJECTSEARCHPATHS" :registry "PROJMODE" :registry
                    "PROMPTMENU" :registry "PROMPTMENUFLAGS" :registry "PROMPTOPTIONFORMAT" :registry
                    "PROMPTOPTIONTRANSLATEKEYWORDS" :registry "PROPAGATESEARCHSPACE" :registry "PROPAGATETOLERANCE" :registry
                    "PROPERTYPREVIEW" :registry "PROPERTYPREVIEWDELAY" :registry "PROPERTYPREVIEWOBJLIMIT" :registry
                    "PROPOBJLIMIT" :registry "PROPPREVTIMEOUT" :registry "PROPUNITS" :registry
                    "PROXYGRAPHICS" :drawing "PROXYNOTICE" :registry "PROXYSERVERENABLED" :registry
                    "PROXYSERVERHTTP" :registry "PROXYSERVERHTTPPORT" :registry "PROXYSERVERHTTPS" :registry
                    "PROXYSERVERHTTPSPORT" :registry "PROXYSERVERPASSWORD" :registry "PROXYSERVERUSER" :registry
                    "PROXYSHOW" :registry "PROXYWEBSEARCH" :registry "PSLTSCALE" :drawing
                    "PSOLHEIGHT" :drawing "PSOLWIDTH" :drawing "PSTYLEMODE" :drawing
                    "PSTYLEPOLICY" :registry "PSVPSCALE" :drawing "PUBLISHALLSHEETS" :registry
                    "PUBLISHCOLLATE" :registry "PUBLISHHATCH" :registry "PUCSBASE" :drawing
                    "PUSHTODOCSSTATE" :registry "QAFLAGS" :registry "QCSTATE" :not-saved
                    "QPLOCATION" :registry "QPMODE" :registry "QTEXTMODE" :drawing
                    "QUADCOMMANDLAUNCH" :registry "QUADDISPLAY" :registry "QUADEXPANDDELAY" :registry
                    "QUADEXPANDTABDELAY" :registry "QUADGOTRANSPARENT" :registry "QUADHIDEDELAY" :registry
                    "QUADHIDEMARGIN" :registry "QUADICONSIZE" :not-saved "QUADICONSPACE" :registry
                    "QUADMOSTRECENTITEMS" :registry "QUADPOPUPCORNER" :registry "QUADSHOWDELAY" :registry
                    "QUADWIDTH" :registry "QVDRAWINGPIN" :registry "QVLAYOUTPIN" :registry
                    "R12SAVEACCURACY" :registry "R12SAVEDEVIATION" :registry "RASTERDPI" :registry
                    "RASTERPERCENT" :registry "RASTERPREVIEW" :registry "RASTERTHRESHOLD" :registry
                    "REALTIMESPEEDUP" :registry "REALWORLDSCALE" :drawing "REBUILD2DCV" :registry
                    "REBUILD2DDEGREE" :registry "REBUILD2DOPTION" :registry "REBUILDDEGREEU" :registry
                    "REBUILDDEGREEV" :registry "REBUILDOPTIONS" :registry "REBUILDU" :registry
                    "REBUILDV" :registry "RECENTFILES" :registry "RECENTPATH" :registry
                    "RECOVERAUTO" :registry "RECOVERYMODE" :registry "REDHILITEFULL_EDGE_ALPHA" :registry
                    "REDHILITEFULL_EDGE_COLOR" :registry "REDHILITEFULL_EDGE_SHOWHIDDEN" :registry "REDHILITEFULL_EDGE_SMOOTHING" :registry
                    "REDHILITEFULL_EDGE_THICKNESS" :registry "REDHILITEFULL_FACE_ALPHA" :registry "REDHILITEFULL_FACE_COLOR" :registry
                    "REDHILITEPARTIAL_SELECTEDEDGEGLOW_ALPHA" :registry "REDHILITEPARTIAL_SELECTEDEDGEGLOW_COLOR" :registry "REDHILITEPARTIAL_SELECTEDEDGEGLOW_SMOOTHING" :registry
                    "REDHILITEPARTIAL_SELECTEDEDGEGLOW_THICKNESS" :registry "REDHILITEPARTIAL_SELECTEDEDGE_ALPHA" :registry "REDHILITEPARTIAL_SELECTEDEDGE_COLOR" :registry
                    "REDHILITEPARTIAL_SELECTEDEDGE_SHOWGLOW" :registry "REDHILITEPARTIAL_SELECTEDEDGE_SMOOTHING" :registry "REDHILITEPARTIAL_SELECTEDEDGE_THICKNESS" :registry
                    "REDHILITEPARTIAL_SELECTEDFACE_ALPHA" :registry "REDHILITEPARTIAL_SELECTEDFACE_COLOR" :registry "REDHILITEPARTIAL_UNSELECTEDEDGE_SHOWHIDDEN" :registry
                    "REDHILITE_DUCSLOCKED_FACE_ALPHA" :registry "REDHILITE_DUCSLOCKED_FACE_COLOR" :registry "REDHILITE_HIDDENEDGE_ALPHA" :registry
                    "REDHILITE_HIDDENEDGE_COLOR" :registry "REDSDKLINESMOOTHING" :registry "REDUCELENGTHTYPE" :drawing
                    "REDUCELENGTHVALUE" :drawing "REFEDITLOCKNOTINWORKSET" :registry "REFEDITNAME" :not-saved
                    "REFPATHTYPE" :registry "REGENMODE" :drawing "REGEXPAND" :registry
                    "REMEMBERFOLDERS" :registry "RENDERCOMPOSITIONMATERIAL" :drawing "RENDERENVSTATE" :not-saved
                    "RENDERLEVEL" :drawing "RENDERLIGHTCALC" :drawing "RENDERMATERIALDOWNLOAD" :registry
                    "RENDERMATERIALSPATH" :registry "RENDERPREFSSTATE" :not-saved "RENDERTARGET" :drawing
                    "RENDERTIME" :drawing "RENDERUSERLIGHTS" :registry "RENDERUSINGHARDWARE" :registry
                    "REPORTERROR" :registry "REPORTPANELMODE" :not-saved "RESTORECONNECTIONS" :registry
                    "RESTORELOSTFOCUS" :registry "RETAINEDGRAPHICS" :registry "REVCLOUDAPPROXARCLEN" :registry
                    "REVCLOUDARCSTYLE" :registry "REVCLOUDARCVARIANCE" :registry "REVCLOUDCREATEMODE" :registry
                    "REVCLOUDGRIPS" :registry "REVCLOUDLAYER" :drawing "REVCLOUDMAXARCLENGTH" :registry
                    "REVCLOUDMINARCLENGTH" :registry "REVCLOUDSCALEMODE" :registry "RE_INIT" :not-saved
                    "RHINOVERSION" :registry "RIBBONBGLOAD" :registry "RIBBONCONTEXTSELLIM" :registry
                    "RIBBONDOCKEDHEIGHT" :registry "RIBBONICONRESIZE" :registry "RIBBONPANELMARGIN" :not-saved
                    "RIBBONSELECTMODE" :registry "RIBBONSETTINGSENABLED" :registry "RIBBONSTATE" :registry
                    "ROAMABLEROOTPREFIX" :registry "ROLLOVEROPACITY" :registry "ROLLOVERPARAMS" :registry
                    "ROLLOVERSELECTIONSET" :registry "ROLLOVERTIPS" :registry "RTDISPLAY" :registry
                    "RTISOLATESELECTION" :registry "RTREGENAUTO" :registry "RTROTATIONSPEEDFACTOR" :registry
                    "RUBBERBANDCOLOR" :registry "RUBBERBANDSTYLE" :registry "RUBBERSHEETSENSIBILITY_FOR_OS_X" :registry
                    "RUBBERSHEET_FOR_OS_X" :registry "RULERDISPLAY" :registry "RULERTEXTCOLOR" :registry
                    "RUNASLEVEL" :registry "RVTRFALEVELOFDETAIL" :drawing "RVTVALIDATEBREP" :registry
                    "SAFEMODE" :not-saved "SAVECHANGETOLAYOUT" :registry "SAVEFIDELITY" :registry
                    "SAVEFILE" :registry "SAVEFILEPATH" :registry "SAVEFORMAT" :registry
                    "SAVELAYERSNAPSHOT" :registry "SAVENAME" :not-saved "SAVEONDOCSWITCH" :registry
                    "SAVEROUNDTRIP" :registry "SAVETIME" :registry "SCREENBOXES" :not-saved
                    "SCREENMODE" :not-saved "SCREENSIZE" :not-saved "SCRLHIST" :registry
                    "SDI" :registry "SECTIONOFFSETINC" :drawing "SECTIONRESULTINTERVAL" :drawing
                    "SECTIONSCALE" :registry "SECTIONSETTINGSSEARCHPATH" :registry "SECTIONSHEETSETTEMPLATEIMPERIAL" :registry
                    "SECTIONSHEETSETTEMPLATEMETRIC" :registry "SECTIONTHICKNESSINC" :drawing "SECURELOAD" :registry
                    "SECUREREMOTEACCESS" :registry "SELECTIONANNODISPLAY" :registry "SELECTIONAREA" :registry
                    "SELECTIONAREAOPACITY" :registry "SELECTIONCYCLING" :registry "SELECTIONEFFECT" :registry
                    "SELECTIONEFFECTCOLOR" :registry "SELECTIONMODES" :registry "SELECTIONOFFSCREEN" :registry
                    "SELECTIONPREVIEW" :registry "SELECTIONPREVIEWLIMIT" :registry "SELECTSIMILARMODE" :registry
                    "SETBYLAYERMODE" :registry "SHADEDGE" :drawing "SHADEDIF" :drawing
                    "SHAREDVIEWSTATE" :registry "SHAREVIEWPROPERTIES" :registry "SHAREVIEWTYPE" :registry
                    "SHEETNUMBERLEADINGZEROES" :registry "SHEETSETAUTOBACKUP" :registry "SHEETSETTEMPLATEPATH" :registry
                    "SHORTCUTMENU" :registry "SHORTCUTMENUDURATION" :registry "SHOWDOCTABS" :registry
                    "SHOWFULLPATHINTITLE" :registry "SHOWHIST" :drawing "SHOWIDSPROPERTIESONLY" :drawing
                    "SHOWLAYERUSAGE" :registry "SHOWNEWSTATE" :registry "SHOWPALETTESTATE" :registry
                    "SHOWSCROLLBUTTONS" :registry "SHOWTABCLOSEBUTTON" :registry "SHOWTABCLOSEBUTTONACTIVE" :registry
                    "SHOWTABCLOSEBUTTONALL" :registry "SHOWWINDOWLISTBUTTON" :registry "SHPNAME" :not-saved
                    "SIGWARN" :registry "SINGLETONMODE" :registry "SITELOCATIONVISIBILITY" :drawing
                    "SKETCHFEATURECOPYMODE" :registry "SKETCHINC" :drawing "SKPOLY" :drawing
                    "SKYSTATUS" :drawing "SMASSEMBLYEXPORTMODE" :registry "SMASSEMBLYEXPORTREPORTPATHTYPE" :drawing
                    "SMASSEMBLYEXPORTSOLIDTYPESINREPORTS" :drawing "SMATTRIBUTESLAYERCOLOR" :registry "SMATTRIBUTESLAYERTEXTHEIGHT" :registry
                    "SMATTRIBUTESLAYERTEXTHEIGHTTYPE" :registry "SMBENDANNOTATIONSLAYERCOLOR" :registry "SMBENDANNOTATIONSLAYERTEXTHEIGHT" :registry
                    "SMBENDANNOTATIONSLAYERTEXTHEIGHTTYPE" :registry "SMBENDLINESDOWNLAYERCOLOR" :registry "SMBENDLINESDOWNLAYERLINETYPE" :registry
                    "SMBENDLINESDOWNLAYERLINEWEIGHT" :registry "SMBENDLINESUPLAYERCOLOR" :registry "SMBENDLINESUPLAYERLINETYPE" :registry
                    "SMBENDLINESUPLAYERLINEWEIGHT" :registry "SMBEVELFEATURECOLOR" :registry "SMCOLORBEND" :registry
                    "SMCOLORBENDRELIEF" :registry "SMCOLORBEVEL" :registry "SMCOLORCORNERRELIEF" :registry
                    "SMCOLORFLANGE" :registry "SMCOLORFLANGEREFERENCESIDE" :registry "SMCOLORFORM" :registry
                    "SMCOLORHEM" :registry "SMCOLORJOG" :registry "SMCOLORJUNCTION" :registry
                    "SMCOLORLOFTEDBEND" :registry "SMCOLORMITER" :registry "SMCOLORROLLEDEDGE" :registry
                    "SMCOLORTAB" :registry "SMCOLORWRONGBEND" :registry "SMCOLORWRONGFLANGE" :registry
                    "SMCONTOURSLAYERCOLOR" :registry "SMCONTOURSLAYERLINETYPE" :registry "SMCONTOURSLAYERLINEWEIGHT" :registry
                    "SMCONVERTMAXIMALBEVELANGLE" :drawing "SMCONVERTMINIMALBEVELANGLE" :drawing "SMCONVERTPREFERFORMFEATURES" :drawing
                    "SMCONVERTPREFERHEMFEATURES" :drawing "SMCONVERTPREFERJOGFEATURES" :drawing "SMCONVERTPREFERZEROBENDFEATURES" :drawing
                    "SMCONVERTRECOGNIZEBEVELS" :drawing "SMCONVERTRECOGNIZEHOLES" :drawing "SMCONVERTRECOGNIZERIBCONTROLCURVES" :drawing
                    "SMCONVERTWRONGFEATURETHICKNESSDEVIATIONTYPE" :drawing "SMCONVERTWRONGFEATURETHICKNESSDEVIATIONVALUE" :drawing "SMDEFAULTBENDLINEEXTENTTYPE" :drawing
                    "SMDEFAULTBENDLINEEXTENTVALUE" :drawing "SMDEFAULTBENDRADIUSTYPE" :drawing "SMDEFAULTBENDRADIUSVALUE" :drawing
                    "SMDEFAULTBENDRELIEFWIDTHTYPE" :drawing "SMDEFAULTBENDRELIEFWIDTHVALUE" :drawing "SMDEFAULTBEVELFEATUREUNFOLDMODE" :drawing
                    "SMDEFAULTCORNERRELIEFDIAMETERVALUE" :drawing "SMDEFAULTFLANGESPLITEXTENSIONTYPE" :drawing "SMDEFAULTFLANGESPLITEXTENSIONVALUE" :drawing
                    "SMDEFAULTFLANGESPLITGAPTYPE" :drawing "SMDEFAULTFLANGESPLITGAPVALUE" :drawing "SMDEFAULTFORMFEATUREUNFOLDMODE" :drawing
                    "SMDEFAULTGUSSETDEPTHTYPE" :drawing "SMDEFAULTGUSSETDEPTHVALUE" :drawing "SMDEFAULTGUSSETFILLETRADIUSTYPE" :drawing
                    "SMDEFAULTGUSSETFILLETRADIUSVALUE" :drawing "SMDEFAULTGUSSETTYPE" :drawing "SMDEFAULTGUSSETWIDTHTYPE" :drawing
                    "SMDEFAULTGUSSETWIDTHVALUE" :drawing "SMDEFAULTHEMGAPTYPE" :drawing "SMDEFAULTHEMGAPVALUE" :drawing
                    "SMDEFAULTHEMRELATIVEBENDDEDUCTION" :drawing "SMDEFAULTJOGANGLEVALUE" :drawing "SMDEFAULTJOGHEIGHTTYPE" :drawing
                    "SMDEFAULTJOGHEIGHTVALUE" :drawing "SMDEFAULTJOGRADIUSTYPE" :drawing "SMDEFAULTJOGRADIUSVALUE" :drawing
                    "SMDEFAULTJUNCTIONALIGNMENTTORELIEF" :drawing "SMDEFAULTJUNCTIONGAPTYPE" :drawing "SMDEFAULTJUNCTIONGAPVALUE" :drawing
                    "SMDEFAULTKFACTOR" :drawing "SMDEFAULTLOFTEDBENDNUMBERSAMPLES" :drawing "SMDEFAULTRELIEFEXTENSIONTYPE" :drawing
                    "SMDEFAULTRELIEFEXTENSIONVALUE" :drawing "SMDEFAULTRIBFILLETRADIUSTYPE" :drawing "SMDEFAULTRIBFILLETRADIUSVALUE" :drawing
                    "SMDEFAULTRIBPROFILERADIUSTYPE" :drawing "SMDEFAULTRIBPROFILERADIUSVALUE" :drawing "SMDEFAULTRIBROUNDRADIUSTYPE" :drawing
                    "SMDEFAULTRIBROUNDRADIUSVALUE" :drawing "SMDEFAULTSHARPBENDRADIUSLIMITRATIO" :drawing "SMDEFAULTTABCHAMFERDISTANCETYPE" :drawing
                    "SMDEFAULTTABCHAMFERDISTANCEVALUE" :drawing "SMDEFAULTTABCLEARANCETYPE" :drawing "SMDEFAULTTABCLEARANCEVALUE" :drawing
                    "SMDEFAULTTABDISTANCETYPE" :drawing "SMDEFAULTTABDISTANCEVALUE" :drawing "SMDEFAULTTABEDGETYPE" :drawing
                    "SMDEFAULTTABFILLETRADIUSTYPE" :drawing "SMDEFAULTTABFILLETRADIUSVALUE" :drawing "SMDEFAULTTABHEIGHTTYPE" :drawing
                    "SMDEFAULTTABHEIGHTVALUE" :drawing "SMDEFAULTTABLENGTHTYPE" :drawing "SMDEFAULTTABLENGTHVALUE" :drawing
                    "SMDEFAULTTABSLOTNUMBER" :drawing "SMDEFAULTTHICKNESS" :drawing "SMEXPORTOSMAPPROXIMATIONACCURACY" :drawing
                    "SMEXPORTOSMMINIMALEDGELENGTH" :drawing "SMFORMFEATURESDOWNCOLOR" :registry "SMFORMFEATURESDOWNLAYERLINETYPE" :registry
                    "SMFORMFEATURESDOWNLAYERLINEWEIGHT" :registry "SMFORMFEATURESUPCOLOR" :registry "SMFORMFEATURESUPLAYERLINETYPE" :registry
                    "SMFORMFEATURESUPLAYERLINEWEIGHT" :registry "SMHEMCREATECLOSEDHEMGAP" :drawing "SMJUNCTIONCREATEHEALCOINCIDENT" :drawing
                    "SMOOTHMESHCONVERT" :registry "SMOOTHMESHGRID" :registry "SMOOTHMESHMAXFACE" :registry
                    "SMOOTHMESHMAXLEV" :registry "SMOVERALLANNOTATIONSLAYERCOLOR" :registry "SMOVERALLANNOTATIONSLAYERLINETYPE" :registry
                    "SMOVERALLANNOTATIONSLAYERLINEWEIGHT" :registry "SMPARAMETRIZEHOLESPARAMETRIZATION" :drawing "SMREPAIRLOFTEDBENDMERGE" :drawing
                    "SMROLLEDEDGEANNOTATIONSLAYERCOLOR" :registry "SMROLLEDEDGEANNOTATIONSLAYERTEXTHEIGHT" :registry "SMROLLEDEDGEANNOTATIONSLAYERTEXTHEIGHTTYPE" :registry
                    "SMROLLEDEDGELINESDOWNLAYERCOLOR" :registry "SMROLLEDEDGELINESDOWNLAYERLINETYPE" :registry "SMROLLEDEDGELINESDOWNLAYERLINEWEIGHT" :registry
                    "SMROLLEDEDGELINESUPLAYERCOLOR" :registry "SMROLLEDEDGELINESUPLAYERLINETYPE" :registry "SMROLLEDEDGELINESUPLAYERLINEWEIGHT" :registry
                    "SMSMARTFEATURES" :registry "SMSPLITAMBIGUOUSINPUT" :drawing "SMSPLITCONVERTBENDTOJUNCTION" :drawing
                    "SMSPLITHEALCOINCIDENT" :drawing "SMSPLITORTHOGONALBENDSPLIT" :drawing "SMTARGETCAM" :registry
                    "SMUNFOLDAPPEARANCE" :registry "SNAPANG" :drawing "SNAPBASE" :drawing
                    "SNAPGRIDLEGACY" :registry "SNAPISOPAIR" :drawing "SNAPMARKERCOLOR" :registry
                    "SNAPMARKERSIZE" :registry "SNAPMARKERTHICKNESS" :registry "SNAPMODE" :drawing
                    "SNAPSTYL" :drawing "SNAPTYPE" :registry "SNAPUNIT" :drawing
                    "SOLIDCHECK" :not-saved "SOLIDHIST" :drawing "SORTENTS" :drawing
                    "SORTORDER" :registry "SPAADJUSTMODE" :registry "SPACESWITCH" :not-saved
                    "SPACHECKLEVEL" :registry "SPAGRIDASPECTRATIO" :registry "SPAGRIDMODE" :registry
                    "SPAMAXFACETEDGELENGTH" :registry "SPAMAXNUMGRIDLINES" :registry "SPAMINUGRIDLINES" :registry
                    "SPAMINVGRIDLINES" :registry "SPANORMALTOL" :registry "SPASURFACETOL" :registry
                    "SPATRIANGMODE" :registry "SPAUSEFACETRES" :registry "SPLDEGREE" :not-saved
                    "SPLFRAME" :drawing "SPLINESEGS" :drawing "SPLINETYPE" :drawing
                    "SPLKNOTS" :not-saved "SPLMETHOD" :not-saved "SPLPERIODIC" :registry
                    "SRCHPATH" :registry "SSFOUND" :not-saved "SSLOCATE" :registry
                    "SSMAUTOOPEN" :registry "SSMOPENMODE" :registry "SSMPOLLTIME" :registry
                    "SSMSHEETSTATUS" :registry "SSMSTATE" :not-saved "STACKPANELTYPE" :not-saved
                    "STAMPFONTSIZE" :registry "STAMPFONTSTYLE" :registry "STAMPFOOTER" :registry
                    "STAMPFOOTEROFFSETX" :registry "STAMPFOOTEROFFSETY" :registry "STAMPHEADER" :registry
                    "STAMPHEADEROFFSETX" :registry "STAMPHEADEROFFSETY" :registry "STAMPUNITS" :registry
                    "STANDARDSOPTIONS" :registry "STANDARDSVIOLATION" :registry "STARTINFOLDER" :registry
                    "STARTMODE" :registry "STARTUP" :registry "STATUSBAR" :registry
                    "STEPSIZE" :drawing "STEPSPERSEC" :drawing "STLPOSITIVEQUADRANT" :registry
                    "STORYBAR" :drawing "STRUCTURETREECONFIG" :not-saved "STUDENTDRAWING" :not-saved
                    "STYLUSFORCETHRESHOLD" :registry "SUBOBJSELECTIONMODE" :not-saved "SUNPROPERTIESSTATE" :not-saved
                    "SUNSTATUS" :drawing "SUPPRESSALERTS" :not-saved "SURFACEASSOCIATIVITY" :registry
                    "SURFACEASSOCIATIVITYDRAG" :registry "SURFACEAUTOTRIM" :registry "SURFACEMODELINGMODE" :registry
                    "SURFTAB1" :drawing "SURFTAB2" :drawing "SURFTYPE" :drawing
                    "SURFU" :drawing "SURFV" :drawing "SVGBLENDEDGRADIENTS" :registry
                    "SVGCOLORPOLICY" :registry "SVGDEFAULTIMAGEEXTENSION" :registry "SVGGENERICFONTFAMILY" :registry
                    "SVGIMAGEBASE" :registry "SVGIMAGEURL" :registry "SVGLINEWEIGHTSCALE" :registry
                    "SVGOUTPUTHEIGHT" :registry "SVGOUTPUTWIDTH" :registry "SVGPRECISION" :registry
                    "SVGSCALEFACTOR" :registry "SYSCODEPAGE" :not-saved "SYSFLOATING" :registry
                    "SYSMON" :registry "TABCONTROLHEIGHT" :registry "TABLEINDICATOR" :registry
                    "TABLELAYER" :drawing "TABLETOOLBAR" :registry "TABMODE" :not-saved
                    "TABSFIXEDWIDTH" :registry "TANGENTLENGTHTYPE" :drawing "TANGENTLENGTHVALUE" :drawing
                    "TARGET" :drawing "TBCUSTOMIZE" :registry "TBSHOWSHORTCUTS" :registry
                    "TDCREATE" :drawing "TDINDWG" :drawing "TDUCREATE" :drawing
                    "TDUPDATE" :drawing "TDUSRTIMER" :drawing "TDUUPDATE" :drawing
                    "TEETANGENTLENGTHTYPE" :drawing "TEETANGENTLENGTHVALUE" :drawing "TEMPLATEPATH" :registry
                    "TEMPOVERRIDES" :registry "TEMPPREFIX" :registry "TEXTALIGNMODE" :registry
                    "TEXTALIGNSPACING" :registry "TEXTALLCAPS" :registry "TEXTANGLE" :not-saved
                    "TEXTAUTOCORRECTCAPS" :registry "TEXTED" :registry "TEXTEDITMODE" :registry
                    "TEXTEVAL" :not-saved "TEXTFILL" :registry "TEXTGAPSELECTION" :registry
                    "TEXTJUSTIFY" :drawing "TEXTLAYER" :drawing "TEXTOUTPUTFILEFORMAT" :registry
                    "TEXTQLTY" :not-saved "TEXTSIZE" :drawing "TEXTSTYLE" :drawing
                    "TEXTTOATTRIBUTE" :drawing "TEXTUREMAPPATH" :registry "THICKNESS" :drawing
                    "THREADDISPLAY" :registry "THUMBSAVE" :registry "THUMBSIZE" :registry
                    "THUMBSIZE2D" :registry "TILEMODE" :drawing "TILEMODELIGHTSYNCH" :drawing
                    "TIMEZONE" :drawing "TOOLBARMARGIN" :not-saved "TOOLBUTTONSIZE" :not-saved
                    "TOOLICONPADDING" :not-saved "TOOLPALETTEPATH" :registry "TOOLTIPDELAY" :registry
                    "TOOLTIPMERGE" :registry "TOOLTIPS" :registry "TOOLTIPTRANSPARENCY" :registry
                    "TOUCHMODE" :registry "TPSTATE" :not-saved "TRACECURRENT" :not-saved
                    "TRACEDISPLAYMODE" :not-saved "TRACEFADECTL" :registry "TRACEMARKUPFADECTL" :registry
                    "TRACEMODE" :not-saved "TRACEOSNAP" :registry "TRACEPALETTESTATE" :registry
                    "TRACEPAPERCTL" :not-saved "TRACEVPSUPPORT" :registry "TRACEWID" :drawing
                    "TRACKPATH" :registry "TRANSPARENCYDISPLAY" :registry "TRAYICONS" :registry
                    "TRAYNOTIFY" :registry "TRAYTIMEOUT" :registry "TREEDEPTH" :drawing
                    "TREEMAX" :registry "TRIMEDGES" :registry "TRIMEXTENDMODE" :registry
                    "TRIMMODE" :registry "TRUSTEDPATHS" :registry "TSPACEFAC" :not-saved
                    "TSPACETYPE" :registry "TSTACKALIGN" :drawing "TSTACKSIZE" :drawing
                    "TTFASTEXT" :registry "TUTORIALSONSTARTPAGE" :registry "UCS2DDISPLAYSETTING" :registry
                    "UCS3DPARADISPLAYSETTING" :registry "UCS3DPERPDISPLAYSETTING" :registry "UCSAXISANG" :registry
                    "UCSBASE" :drawing "UCSDETECT" :registry "UCSFOLLOW" :drawing
                    "UCSICON" :drawing "UCSICONPOS" :registry "UCSNAME" :drawing
                    "UCSORG" :drawing "UCSORTHO" :registry "UCSSELECTMODE" :registry
                    "UCSVIEW" :registry "UCSVP" :drawing "UCSXDIR" :drawing
                    "UCSYDIR" :drawing "UNDOCTL" :not-saved "UNDOMARKS" :not-saved
                    "UNITESURFACES" :not-saved "UNITMODE" :drawing "UOSNAP" :registry
                    "UPDATETHUMBNAIL" :drawing "USECOMMUNICATOR" :registry "USENEWSTATUSBAR" :registry
                    "USERI1" :drawing "USERI2" :drawing "USERI3" :drawing
                    "USERI4" :drawing "USERI5" :drawing "USERR1" :drawing
                    "USERR2" :drawing "USERR3" :drawing "USERR4" :drawing
                    "USERR5" :drawing "USERS1" :not-saved "USERS2" :not-saved
                    "USERS3" :not-saved "USERS4" :not-saved "USERS5" :not-saved
                    "USESTANDARDOPENFILEDIALOG" :registry "VBAMACROS" :registry "VENDORNAME" :not-saved
                    "VERBOSEBIMSECTIONUPDATE" :registry "VERSIONCONTROLCONFIGPATH" :registry "VERSIONCONTROLDOWNLOADPATH" :registry
                    "VERSIONCUSTOMIZABLEFILES" :registry "VIEWBACKSTATUS" :not-saved "VIEWCTR" :drawing
                    "VIEWDIR" :drawing "VIEWFWDSTATUS" :not-saved "VIEWMODE" :drawing
                    "VIEWPORTLAYER" :drawing "VIEWSIZE" :drawing "VIEWSKETCHMODE" :registry
                    "VIEWTWIST" :drawing "VIEWUPDATEAUTO" :drawing "VISRETAIN" :drawing
                    "VISRETAINMODE" :registry "VOLUMEPREC" :registry "VOLUMEUNITS" :registry
                    "VPCONTROL" :registry "VPLAYEROVERRIDES" :drawing "VPLAYEROVERRIDESMODE" :registry
                    "VPMAXIMIZEDSTATE" :not-saved "VPROTATEASSOC" :registry "VSACURVATUREHIGH" :drawing
                    "VSACURVATURELOW" :drawing "VSACURVATURETYPE" :drawing "VSADRAFTANGLEHIGH" :drawing
                    "VSAZEBRACOLOR1" :drawing "VSAZEBRACOLOR2" :drawing "VSAZEBRADIRECTION" :drawing
                    "VSAZEBRASIZE" :drawing "VSAZEBRATYPE" :drawing "VSBACKGROUNDS" :drawing
                    "VSEDGECOLOR" :drawing "VSEDGEJITTER" :drawing "VSEDGELEX" :drawing
                    "VSEDGES" :drawing "VSEDGESMOOTH" :drawing "VSFACECOLORMODE" :drawing
                    "VSFACEHIGHLIGHT" :drawing "VSFACEOPACITY" :drawing "VSFACESTYLE" :drawing
                    "VSHALOGAP" :drawing "VSINTERSECTIONCOLOR" :drawing "VSINTERSECTIONEDGES" :drawing
                    "VSINTERSECTIONLTYPE" :drawing "VSISOONTOP" :drawing "VSLIGHTINGQUALITY" :drawing
                    "VSMATERIALMODE" :drawing "VSMAX" :drawing "VSMIN" :drawing
                    "VSMONOCOLOR" :drawing "VSOCCLUDEDCOLOR" :drawing "VSOCCLUDEDEDGES" :drawing
                    "VSOCCLUDEDLTYPE" :drawing "VSSHADOWS" :drawing "VSSILHEDGES" :drawing
                    "VSSILHWIDTH" :drawing "VSSTATE" :not-saved "VTDURATION" :registry
                    "VTENABLE" :registry "VTFPS" :registry "WARNINGMESSAGES" :registry
                    "WBLOCKCREATEMODE" :registry "WHIPARC" :registry "WHIPTHREAD" :registry
                    "WINDOWAREACOLOR" :registry "WIPEOUTFRAME" :drawing "WMFBKGND" :not-saved
                    "WMFFOREGND" :not-saved "WMFTTFASTEXT" :registry "WNDLMAIN" :registry
                    "WNDLSCRL" :not-saved "WNDLTEXT" :registry "WNDPMAIN" :registry
                    "WNDPTEXT" :registry "WNDSMAIN" :registry "WNDSTEXT" :registry
                    "WORKINGFOLDER" :registry "WORKSPACELABEL" :registry "WORLDUCS" :not-saved
                    "WORLDVIEW" :drawing "WRITESTAT" :not-saved "WSAUTOSAVE" :registry
                    "WSCURRENT" :registry "XCLIPFRAME" :drawing "XCOMPAREBAKPATH" :registry
                    "XCOMPAREBAKSIZE" :registry "XCOMPARECOLORMODE" :registry "XCOMPAREENABLE" :registry
                    "XDWGFADECTL" :registry "XEDIT" :drawing "XFADECTL" :registry
                    "XLOADCTL" :registry "XLOADPATH" :registry "XNOTIFYTIME" :registry
                    "XREFCTL" :registry "XREFLAYER" :drawing "XREFNOTIFY" :registry
                    "XREFOVERRIDE" :drawing "XREFREGAPPCTL" :registry "XREFTYPE" :registry
                    "ZOOMFACTOR" :registry "ZOOMWHEEL" :registry "_TOOLPALETTEPATH" :registry
                    ) by #'cddr
          do (setf (gethash name table) tier))
    table)
  "Name -> scope tier (:DRAWING / :REGISTRY / :NOT-SAVED) of each inventoried
system variable (1836): inventory :saved-in, :preference counted as :registry,
:session as :not-saved (D1 §4, C4).")

(defun sysvar-scope-tier (name)
  "The scope tier of system variable NAME, or NIL when it is not inventoried."
  (values (gethash name *sysvar-scope-tiers*)))
