;;;; -*- Mode: Lisp; coding: utf-8 -*-
;;;; GENERATED by clautolisp/tools/generate-template-defaults.py -- DO NOT EDIT.
;;;; Imperial-template (acad.dwt) values of the (:drawing) sysvars, from the
;;;; inventory's documented "default AutoCAD X (imperial)". Regenerate:
;;;;   python3 tools/generate-template-defaults.py \
;;;;     ../autolisp-spec/documentation/system-variables-inventory.sexp \
;;;;     cador/source/template-defaults.lisp
;;;; Left on the catalogue stand-in (no imperial value stated): CIRCULARARROWHEADLENGTH CIRCULARARROWHEADWIDTH CIRCULARARROWLEADERRADIUS CIRCULARARROWTHICKNESS CMLSCALE CVIEWDETAILSTYLE DEFAULTSPACEHEIGHT DIMDSEP HPNAME INTERIORELEVATIONMINLENGTH INTERIORELEVATIONOFFSET LINEARARROWHEADLENGTH LINEARARROWHEADWIDTH LINEARARROWTHICKNESS SMDEFAULTTHICKNESS SMEXPORTOSMAPPROXIMATIONACCURACY SMEXPORTOSMMINIMALEDGELENGTH UCSNAME

(in-package #:clautolisp.cador)

(defparameter *imperial-template-defaults*
  '(
    ("CENTEREXE" . 0.1200d0)
    ("DIMALTD" . 2)
    ("DIMALTF" . 25.4000d0)
    ("DIMALTTD" . 2)
    ("DIMASZ" . 0.1800d0)
    ("DIMCEN" . 0.0900d0)
    ("DIMDEC" . 4)
    ("DIMDLI" . 0.3800d0)
    ("DIMEXE" . 0.1800d0)
    ("DIMEXO" . 0.0625d0)
    ("DIMGAP" . 0.0900d0)
    ("DIMSTYLE" . "Standard")
    ("DIMTAD" . 0)
    ("DIMTDEC" . 4)
    ("DIMTIH" . 1)
    ("DIMTOFL" . 0)
    ("DIMTOH" . 1)
    ("DIMTOLJ" . 1)
    ("DIMTXT" . 0.1800d0)
    ("DIMTZIN" . 0)
    ("DIMZIN" . 0)
    ("GRIDUNIT" . (0.5000d0 0.5000d0))
    ("INSUNITS" . 1)
    ("LIMMAX" . (12.0000d0 9.0000d0))
    ("MEASUREMENT" . 0)
    ("PSOLHEIGHT" . 4.0000d0)
    ("PSOLWIDTH" . 0.2500d0)
    ("SNAPUNIT" . (0.5000d0 0.5000d0))
    ("TEXTSIZE" . 0.2000d0)
    )
  "(NAME . VALUE): what a fresh imperial AutoCAD drawing holds in the
drawing-dependent sysvars the catalogue can only stand in for.")
