(defpackage #:clautolisp.autolisp-reader
  (:use #:cl)
  (:export
   #:make-reader-options
   #:reader-options
   #:reader-options-token-mode
   #:reader-options-retain-comments-p
   #:reader-options-recover-malformed-p
   #:reader-options-warn-on-integer-overflow-p
   #:reader-options-extended-string-escapes-p
   #:reader-options-canonical-case
   #:reader-options-source-name
   #:source-span
   #:source-span-source-name
   #:source-span-start-line
   #:source-span-start-column
   #:source-span-end-line
   #:source-span-end-column
   #:diagnostic
   #:diagnostic-severity
   #:diagnostic-code
   #:diagnostic-message
   #:diagnostic-span
   #:token
   #:token-kind
   #:token-lexeme
   #:token-value
   #:token-span
   #:token-acceptance-mode
   #:token-overflowed-integer-p
   #:comment-object
   #:comment-object-text
   #:comment-object-span
   #:comment-object-kind
   #:dot-object
   #:dot-object-lexeme
   #:dot-object-span
   #:symbol-object
   #:symbol-object-original-name
   #:symbol-object-canonical-name
   #:symbol-object-span
   #:symbol-object-acceptance-mode
   #:string-object
   #:string-object-value
   #:string-object-lexeme
   #:string-object-span
   #:string-object-acceptance-mode
   #:integer-object
   #:integer-object-value
   #:integer-object-lexeme
   #:integer-object-span
   #:integer-object-acceptance-mode
   #:real-object
   #:real-object-value
   #:real-object-lexeme
   #:real-object-span
   #:real-object-acceptance-mode
   #:real-object-overflowed-integer-p
   #:cons-object
   #:cons-object-elements
   #:cons-object-tail
   #:cons-object-dotted-p
   #:cons-object-span
   #:quote-object
   #:quote-object-object
   #:quote-object-span
   #:concrete-list-object
   #:concrete-list-object-items
   #:concrete-list-object-span
   #:read-result
   #:read-result-objects
   #:read-result-diagnostics
   #:tokenize-string
   #:tokenize-stream
   #:tokenize-file
   #:read-forms-from-string
   #:read-forms-from-stream
   #:read-forms-from-file
   #:read-concrete-from-string
   #:read-concrete-from-stream
   #:read-concrete-from-file
   #:autolisp-dialect
   #:make-autolisp-dialect
   #:autolisp-dialect-name
   #:autolisp-dialect-token-mode
   #:autolisp-dialect-extended-string-escapes-p
   #:autolisp-dialect-warn-on-integer-overflow-p
   #:autolisp-dialect-canonical-case
   #:autolisp-dialect-hex-float-atof-p
   #:autolisp-dialect-open-ccs-mode-p
   #:autolisp-dialect-unbound-variable-mode
   #:autolisp-dialect-default-source-encoding
   #:autolisp-dialect-default-file-encoding
   #:find-autolisp-dialect
   #:reader-options-from-dialect
   #:autolisp-dialect-strict
   #:autolisp-dialect-autocad-2026
   #:autolisp-dialect-bricscad-v26))

(defpackage #:clautolisp.autolisp-reader.internal
  (:use #:cl)
  (:import-from #:uiop #:with-safe-io-syntax)
  (:export
   #:combine-spans
   #:clone-reader-options
   #:decode-and-normalize-stream
   #:decode-and-normalize-file
   #:diagnostic
   #:make-comment-object
   #:make-concrete-list-object
   #:make-cons-object
   #:make-diagnostic
   #:make-dot-object
   #:make-integer-object
   #:make-quote-object
   #:make-read-result
   #:make-reader-options
   #:make-real-object
   #:make-source-span
   #:make-string-object
   #:make-symbol-object
   #:make-token
   #:normalize-line-endings
   #:parse-concrete-tokens
   #:parse-form-tokens
   #:read-result
   #:reader-options
   #:scan-tokens
   #:source-span
   #:token
   #:autolisp-dialect
   #:make-autolisp-dialect
   #:autolisp-dialect-name
   #:autolisp-dialect-token-mode
   #:autolisp-dialect-extended-string-escapes-p
   #:autolisp-dialect-warn-on-integer-overflow-p
   #:autolisp-dialect-canonical-case
   #:autolisp-dialect-hex-float-atof-p
   #:autolisp-dialect-open-ccs-mode-p
   #:autolisp-dialect-unbound-variable-mode
   #:autolisp-dialect-default-source-encoding
   #:autolisp-dialect-default-file-encoding
   #:find-autolisp-dialect
   #:reader-options-from-dialect
   #:*autolisp-dialect-strict*
   #:*autolisp-dialect-autocad-2026*
   #:*autolisp-dialect-bricscad-v26*))
